/**
 * The top-level keys core's own gamedata uses, per record file.
 *
 * GENERATED by scripts/gen-record-keys.mjs from packages/content/pack. Do not
 * edit by hand; record-keys.test.ts re-derives it from the shipped pack and
 * fails in both directions, so an edit here is undone by the next run either
 * way.
 *
 * This exists so a mod can ADD a key. Composition has always carried an
 * unrecognised key through untouched, but every binder then dropped it on the
 * floor - so a mod could write `"bleed": {...}` on a dagger, see no error, and
 * find nothing at runtime. Subtracting this table from a record's keys is what
 * separates "core reads this" from "a mod added this", and the leftovers ride
 * along on the bound record as `ext`.
 */

/** file stem -> the keys core's data uses, sorted. */
export const CORE_RECORD_KEYS: Readonly<Record<string, readonly string[]>> = {
  "activation": ["aim", "desc", "effect", "level", "msg", "name", "power"],
  "artifact": ["act", "alloc", "armor", "attack", "base-object", "brand", "cost", "curse", "desc", "flags", "graphics", "level", "msg", "name", "slay", "time", "values", "weight"],
  "blow_effects": ["desc", "effect-type", "eval", "lash-type", "lore-color-base", "lore-color-immune", "lore-color-resist", "name", "power", "resist"],
  "blow_methods": ["act", "cut", "desc", "miss", "msg", "name", "phys", "stun"],
  "body": ["body", "slot"],
  "brand": ["code", "multiplier", "name", "o-multiplier", "power", "resist-flag", "verb", "vuln-flag"],
  "chest_trap": ["code", "destroy", "effect", "level", "magic", "msg", "msg-death", "name"],
  "class": ["book", "equip", "hitdie", "magic", "max-attacks", "min-weight", "name", "obj-flags", "player-flags", "skill-device", "skill-dig", "skill-disarm-magic", "skill-disarm-phys", "skill-melee", "skill-save", "skill-search", "skill-shoot", "skill-stealth", "skill-throw", "stats", "strength-multiplier", "title"],
  "constants": ["carry-cap", "dun-gen", "level-max", "melee-critical", "melee-critical-level", "mon-gen", "mon-play", "o-melee-critical", "o-melee-critical-level", "o-ranged-critical", "o-ranged-critical-level", "obj-make", "player", "ranged-critical", "ranged-critical-level", "store", "world"],
  "curse": ["combat", "conflict", "conflict-flags", "desc", "effect", "flags", "msg", "name", "time", "type", "values"],
  "dungeon_profile": ["alloc", "min-level", "name", "params", "room", "streamer", "tunnel"],
  "ego_item": ["alloc", "brand", "combat", "desc", "flags", "flags-off", "info", "item", "min-combat", "min-values", "name", "slay", "type", "values"],
  "flavor": ["fixed", "flavor", "kind"],
  "hints": ["H"],
  "history": ["chart", "phrase"],
  "monster": ["armor-class", "base", "blow", "color", "color-cycle", "depth", "desc", "drop", "drop-base", "drop-order", "experience", "flags", "flags-off", "friends", "friends-base", "glyph", "hearing", "hit-points", "innate-freq", "light", "message-invis", "message-vis", "mimic", "name", "plural", "rarity", "shape", "sleepiness", "smell", "speed", "spell-freq", "spell-power", "spells"],
  "monster_base": ["desc", "flags", "glyph", "name", "pain"],
  "monster_spell": ["effect", "hit", "lore", "lore-color-base", "lore-color-immune", "lore-color-resist", "message-invis", "message-miss", "message-save", "message-vis", "msgt", "name", "power-cutoff"],
  "names": ["section", "word"],
  "object": ["alloc", "armor", "attack", "charges", "cost", "curse", "desc", "effect", "flags", "graphics", "level", "msg", "name", "pile", "power", "pval", "slay", "time", "type", "values", "vis-msg", "weight"],
  "object_base": ["break", "flags", "graphics", "name"],
  "object_property": ["adjective", "bindui", "code", "desc", "id-type", "msg", "mult", "name", "neg-adjective", "power", "subtype", "type", "type-mult"],
  "p_race": ["age", "exp", "height", "history", "hitdie", "infravision", "name", "obj-flags", "player-flags", "skill-device", "skill-dig", "skill-disarm-magic", "skill-disarm-phys", "skill-melee", "skill-save", "skill-search", "skill-shoot", "skill-stealth", "skill-throw", "stats", "values", "weight"],
  "pain": ["message", "type"],
  "pit": ["alloc", "color", "flags-ban", "flags-req", "innate-freq", "mon-ban", "mon-base", "name", "obj-rarity", "room", "spell-ban", "spell-req"],
  "player_property": ["bindui", "code", "desc", "name", "type", "value"],
  "player_timed": ["brand", "desc", "fail", "flag-synonym", "flags", "grade", "lower-bound", "msgt", "name", "on-begin-effect", "on-decrease", "on-end", "on-end-effect", "on-increase", "resist", "slay"],
  "projection": ["blind-desc", "code", "color", "damage-cap", "denominator", "desc", "divisor", "lash-desc", "msgt", "name", "numerator", "obvious", "player-desc", "type", "wake"],
  "quest": ["level", "name", "number", "race"],
  "realm": ["book-noun", "name", "spell-noun", "stat", "verb"],
  "room_template": ["D", "columns", "doors", "flags", "name", "rating", "rows", "tval", "type"],
  "shape": ["blow", "combat", "effect", "effect-msg", "name", "obj-flags", "player-flags", "skill-disarm-magic", "skill-disarm-phys", "skill-melee", "skill-save", "values"],
  "slay": ["code", "melee-verb", "multiplier", "name", "o-multiplier", "power", "race-flag", "range-verb"],
  "store": ["always", "buy", "normal", "owner", "slots", "store", "turnover"],
  "summon": ["base", "desc", "fallback", "msgt", "name", "race-flag", "uniques"],
  "terrain": ["code", "confused-msg", "desc", "die-msg", "digging", "flags", "graphics", "hurt-msg", "look-in-preposition", "look-prefix", "mimic", "name", "priority", "resist-flag", "run-msg", "walk-msg"],
  "trap": ["appear", "desc", "effect", "effect-xtra", "flags", "graphics", "msg", "msg-bad", "msg-good", "msg-xtra", "name", "save", "visibility"],
  "ui_entry": ["category", "combine", "desc", "flags", "label", "label2", "label5", "name", "parameter", "priority", "renderer", "template"],
  "ui_entry_base": ["category", "combine", "desc", "flags", "name", "renderer"],
  "ui_entry_renderer": ["code", "colors", "labelcolors", "name", "ndigit", "sign", "symbols"],
  "ui_knowledge": ["mcat-include-base", "mcat-include-flag", "monster-category"],
  "vault": ["D", "columns", "flags", "max-depth", "min-depth", "name", "rating", "rows", "type"],
  "visuals": ["cycle", "flicker"],
  "world": ["level"],
};

/**
 * The keys of `record` that core does not know about, or undefined when there
 * are none.
 *
 * Undefined rather than an empty object so the overwhelmingly common case - an
 * unmodded record - adds no allocation and no property, and so `ext` being
 * present means something.
 *
 * An UNKNOWN FILE yields undefined rather than treating every key as an
 * extension: a file core ships no data for is one this table cannot speak
 * about, and guessing there would hand a mod an `ext` full of core's own
 * fields.
 *
 * ONLY NAMESPACED KEYS QUALIFY. `bleed` on a dagger is not an extension field;
 * `gore:bleed` is. Without that rule "unknown to core" would be the whole
 * test, and a misspelling of one of core's own keys (`atack`) would arrive here
 * looking exactly like a deliberate new field - so the author would see it in
 * `ext`, believe the patch worked, and never learn the real field went
 * untouched. The namespace is also what stops two mods coining the same word
 * from silently overwriting each other. The rule is enforced at composition
 * (mod-sdk fields.ts): the owning mod must DECLARE the field, and another pack
 * may write it only when it declares that owner as a dependency. This is the
 * same rule at the other end, so a record that reached core by some other route
 * cannot bypass it.
 */
export function extensionData(
  file: string,
  record: object,
): Readonly<Record<string, unknown>> | undefined {
  const known = CORE_RECORD_KEYS[file];
  if (known === undefined) return undefined;
  let out: Record<string, unknown> | undefined;
  for (const [key, value] of Object.entries(record)) {
    if (!key.includes(":") || known.includes(key)) continue;
    out ??= {};
    out[key] = value;
  }
  return out === undefined ? undefined : Object.freeze(out);
}
