/**
 * The blueprint table, re-derived from the shipped pack.
 *
 * WHY RE-DERIVE RATHER THAN SPOT-CHECK. The table is generated, so a test that
 * asserted "object has 375 records" would pass forever by reading the same
 * generated constant twice. The only check with any content is the one that
 * reads the PACK and rebuilds the answer, which is why this file re-implements
 * the counting rather than importing the generator: an error shared by the
 * generator and the test is one neither would find.
 */

import { readdirSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { RECORD_BLUEPRINTS } from "./blueprints.js";
import { BLUEPRINT_FILES, fieldUsage, requiredFields, templateRecord } from "./authoring.js";

/**
 * core's generated key table, READ AS A FILE rather than imported.
 *
 * mod-sdk has no dependency on core and its tsconfig rootDir is its own src,
 * so an import would break the build - which is the same reason fields.test.ts
 * reads this file too. Parsing the generated table is enough for the one thing
 * asserted below: that the two generated tables name the same keys.
 */
function coreRecordKeys(): Record<string, string[]> {
  const text = readFileSync(new URL("../../core/src/mod/record-keys.ts", import.meta.url), "utf8");
  const body = text.slice(text.indexOf("CORE_RECORD_KEYS"), text.indexOf("};"));
  const out: Record<string, string[]> = {};
  for (const line of body.split(/\r?\n/)) {
    const m = /^\s*"([^"]+)": \[(.*)\],$/.exec(line);
    if (m === null) continue;
    out[m[1] as string] = [...(m[2] as string).matchAll(/"([^"]*)"/g)].map((k) => k[1] as string);
  }
  return out;
}

const packDir = new URL("../../content/pack/", import.meta.url);

function packRecords(stem: string): Record<string, unknown>[] {
  const raw: unknown = JSON.parse(readFileSync(new URL(`${stem}.json`, packDir), "utf8"));
  const records = Array.isArray(raw) ? raw : (raw as { records?: unknown[] }).records;
  if (!Array.isArray(records)) return [];
  return records.filter(
    (r): r is Record<string, unknown> => r !== null && typeof r === "object" && !Array.isArray(r),
  );
}

const packFiles = readdirSync(packDir)
  .filter((f) => f.endsWith(".json"))
  .map((f) => f.replace(/\.json$/, ""))
  .filter((stem) => packRecords(stem).length > 0)
  .sort();

describe("the blueprint table is the shipped pack", () => {
  it("covers exactly the record-bearing files, in both directions", () => {
    expect(BLUEPRINT_FILES).toEqual(packFiles);
  });

  it("counts each file's records", () => {
    for (const stem of packFiles) {
      expect(RECORD_BLUEPRINTS[stem]?.records, stem).toBe(packRecords(stem).length);
    }
  });

  it("counts how many records carry each top-level field", () => {
    for (const stem of packFiles) {
      const counted = new Map<string, number>();
      for (const r of packRecords(stem)) {
        for (const key of Object.keys(r)) counted.set(key, (counted.get(key) ?? 0) + 1);
      }
      const fields = RECORD_BLUEPRINTS[stem]?.fields ?? {};
      expect([...Object.keys(fields)].sort(), stem).toEqual([...counted.keys()].sort());
      for (const [key, n] of counted) {
        expect(fields[key]?.count, `${stem}.${key}`).toBe(n);
      }
    }
  });

  it("agrees with core's own generated key table, file for file", () => {
    /* TWO GENERATED TABLES FROM ONE PACK. core's CORE_RECORD_KEYS decides what
     * `ext` carries; this package's blueprints decide what an author is told.
     * They are generated by different scripts in different packages, and the
     * day they disagree is the day a field is an extension at one end and a
     * core field at the other. */
    const theirs = coreRecordKeys();
    expect(Object.keys(theirs).length, "the table parsed").toBeGreaterThan(40);
    for (const stem of packFiles) {
      const mine = Object.keys(RECORD_BLUEPRINTS[stem]?.fields ?? {}).sort();
      expect(mine, stem).toEqual([...(theirs[stem] ?? [])].sort());
    }
  });
});

describe("required means every record has it", () => {
  it("is a measurement, not a list", () => {
    for (const stem of packFiles) {
      const records = packRecords(stem);
      const measured = [...new Set(records.flatMap((r) => Object.keys(r)))]
        .filter((key) => records.every((r) => key in r))
        .sort();
      expect(requiredFields(stem), stem).toEqual(measured);
    }
  });

  it("names the fields a monster and an object cannot do without", () => {
    /* The control on the measurement above: it would also pass if every file
     * required nothing. */
    expect(requiredFields("monster")).toContain("base");
    expect(requiredFields("object")).toContain("type");
    expect(requiredFields("object")).toContain("graphics");
  });
});

describe("the observed value sets", () => {
  it("hold only strings and booleans, never numbers", () => {
    /* A small set of numbers is a coincidence, not a vocabulary, and offering
     * one as "core's values" would invite an author to pick from thirty
     * arbitrary armour classes. Numbers get a range instead. */
    const walk = (shape: { values?: readonly unknown[]; fields?: Record<string, unknown>; items?: unknown }): void => {
      for (const v of shape.values ?? []) {
        expect(typeof v).not.toBe("number");
      }
      for (const kid of Object.values(shape.fields ?? {})) walk(kid as never);
      if (shape.items !== undefined) walk(shape.items as never);
    };
    for (const bp of Object.values(RECORD_BLUEPRINTS)) {
      for (const shape of Object.values(bp.fields)) walk(shape);
    }
  });

  it("record the vocabulary a nested list actually uses", () => {
    /* ego_item.brand is an array of slay/brand CODES, two levels down. If the
     * generator stopped describing arrays by their elements this would be the
     * first thing to go quiet. */
    expect(RECORD_BLUEPRINTS["ego_item"]?.fields["brand"]?.items?.values).toContain("ACID_3");
    expect(RECORD_BLUEPRINTS["monster"]?.fields["blow"]?.items?.fields?.["method"]?.values)
      .toContain("HIT");
  });
});

describe("templateRecord", () => {
  it("carries every required field of the file", () => {
    for (const stem of packFiles) {
      const t = templateRecord(stem, "required");
      expect(Object.keys(t).sort(), stem).toEqual(requiredFields(stem));
    }
  });

  it("adds the fields most of core's records carry, at the common scope", () => {
    const common = templateRecord("object", "common");
    expect(Object.keys(common)).toContain("alloc");
    expect(Object.keys(templateRecord("object", "required"))).not.toContain("alloc");
  });

  it("leaves `name` empty and fills the rest", () => {
    const t = templateRecord("monster");
    expect(t["name"]).toBe("");
    expect(t["speed"]).toBeTypeOf("number");
  });

  it("writes an empty list rather than a list holding an empty string", () => {
    /* `flags: [""]` is not a hint, it is a value the parser would choke on. */
    const t = templateRecord("monster", "all");
    expect(t["flags"]).toEqual([]);
  });

  it("says nothing about a file core does not ship", () => {
    expect(templateRecord("sludge")).toEqual({});
    expect(requiredFields("sludge")).toEqual([]);
    expect(fieldUsage("sludge")).toEqual([]);
  });
});
