// Generated from reference/lib/customize/sound.prf by
// scripts/gen-sound-prefs.mjs. Do not edit.
//
// The message->sound NAME MAPPING (functional data) from the Dubtrain
// Angband sound config. Each entry is one `sound:<MSG_NAME>:<samples>`
// directive: 'type' is the MSG_ name (message_lookup_by_name), 'sounds' is
// the raw space-separated list of sample base-names (no path, no extension).
//
// NO AUDIO ASSETS are bundled: the Dubtrain .mp3 pack is Creative-Commons
// NON-COMMERCIAL. This repo has commercial intent, so only the name mapping
// is ported. A web front end loads user-supplied audio from a configurable
// base URL (see packages/web/src/sound.ts).

/** One parsed `sound:` directive from sound.prf. */
export interface SoundPrefEntry {
  /** MSG_ name (feeds message_lookup_by_name). */
  readonly type: string;
  /** Space-separated sample base-names, exactly as in the prf. */
  readonly sounds: string;
}

/** Every `sound:` directive from sound.prf, in file order. */
export const SOUND_PREF_ENTRIES: readonly SoundPrefEntry[] = [
  { type: "AMBIENT_DAY", sounds: "amb_thunder_rain" },
  { type: "AMBIENT_NITE", sounds: "amb_guitar_chord amb_thunder_roll" },
  { type: "AMBIENT_DNG1", sounds: "amb_door_iron amb_bell_metal1" },
  { type: "AMBIENT_DNG2", sounds: "amb_bell_tibet1 amb_bell_metal2 amb_gong_strike" },
  { type: "AMBIENT_DNG3", sounds: "amb_bell_tibet2 amb_dungeon_echo amb_pulse_low" },
  { type: "AMBIENT_DNG4", sounds: "amb_bell_tibet3 amb_dungeon_echowet amb_gong_undertone" },
  { type: "AMBIENT_DNG5", sounds: "amb_door_doom amb_gong_chinese amb_gong_low" },
  { type: "STORE1", sounds: "sto_man_hey" },
  { type: "STORE2", sounds: "id_bad_dang" },
  { type: "STORE3", sounds: "sto_man_haha" },
  { type: "STORE4", sounds: "sto_man_whoohaha" },
  { type: "STORE5", sounds: "sto_coins_countertop sto_bell_register1 sto_bell_register2" },
  { type: "STORE_ENTER", sounds: "sto_bell_desk sto_bell_ding sto_bell_dingaling sto_bell_jingles sto_bell_ringing sto_bell_shop" },
  { type: "STORE_HOME", sounds: "plm_door_entrance" },
  { type: "STORE_LEAVE", sounds: "plm_door_bolt" },
  { type: "HIT", sounds: "plc_hit_hay plc_hit_body" },
  { type: "HIT_GOOD", sounds: "plc_hit_anvil" },
  { type: "HIT_GREAT", sounds: "plc_hit_groan" },
  { type: "HIT_SUPERB", sounds: "plc_hit_grunt" },
  { type: "HIT_HI_GREAT", sounds: "plc_hit_grunt2" },
  { type: "HIT_HI_SUPERB", sounds: "plc_hit_anvil2" },
  { type: "MISS", sounds: "plc_miss_arrow2" },
  { type: "SHOOT", sounds: "plc_miss_arrow" },
  { type: "SHOOT_HIT", sounds: "plc_hit_arrow" },
  { type: "HITPOINT_WARN", sounds: "plc_bell_warn" },
  { type: "DEATH", sounds: "plc_die_laugh" },
  { type: "BLIND", sounds: "pls_tone_conk" },
  { type: "CONFUSED", sounds: "pls_man_ugh" },
  { type: "POISONED", sounds: "pls_tone_guiro" },
  { type: "AFRAID", sounds: "pls_man_yell" },
  { type: "PARALYZED", sounds: "pls_man_gulp_new" },
  { type: "DRUGGED", sounds: "pls_breathe_in" },
  { type: "SLOW", sounds: "pls_man_sigh" },
  { type: "STUN", sounds: "pls_bell_mute" },
  { type: "CUT", sounds: "pls_man_argoh" },
  { type: "DRAIN_STAT", sounds: "pls_tone_headstock" },
  { type: "RECOVER", sounds: "pls_bell_chime_new" },
  { type: "SPEED", sounds: "pls_bell_sustain" },
  { type: "SHIELD", sounds: "pls_bell_bowl" },
  { type: "BLESSED", sounds: "sum_ainu_song" },
  { type: "HERO", sounds: "pls_tone_goblet" },
  { type: "BOLD", sounds: "pls_bell_hibell_soft" },
  { type: "BERSERK", sounds: "pls_man_scream2" },
  { type: "PROT_EVIL", sounds: "pls_bell_glass" },
  { type: "INVULN", sounds: "pls_tone_blurk" },
  { type: "SEE_INVIS", sounds: "pls_tone_clave6" },
  { type: "INFRARED", sounds: "pls_tone_clavelo8" },
  { type: "RES_ACID", sounds: "pls_man_sniff" },
  { type: "RES_ELEC", sounds: "pls_tone_elec" },
  { type: "RES_FIRE", sounds: "pls_tone_scrape" },
  { type: "RES_COLD", sounds: "pls_tone_stick" },
  { type: "RES_POIS", sounds: "pls_man_spit" },
  { type: "HUNGRY", sounds: "pls_man_sob" },
  { type: "MONEY1", sounds: "plm_coins_light plm_coins_shake" },
  { type: "MONEY2", sounds: "plm_chain_light plm_coins_pour" },
  { type: "MONEY3", sounds: "plm_coins_dump" },
  { type: "DROP", sounds: "plm_drop_boot" },
  { type: "LEVEL", sounds: "plm_levelup" },
  { type: "STUDY", sounds: "plm_book_pageturn" },
  { type: "TELEPORT", sounds: "plm_chimes_jangle" },
  { type: "QUAFF", sounds: "plm_bottle_clinks plm_cork_pop plm_cork_squeak" },
  { type: "ZAP_ROD", sounds: "plm_zap_rod" },
  { type: "TPOTHER", sounds: "plm_chimes_jangle" },
  { type: "HITWALL", sounds: "plm_wood_thud" },
  { type: "EAT", sounds: "plm_eat_bite" },
  { type: "DIG", sounds: "plm_metal_clank" },
  { type: "OPENDOOR", sounds: "plm_door_bolt plm_door_creak plm_door_dungeon plm_door_entrance plm_door_open plm_door_opening plm_door_rusty plm_door_squeaky" },
  { type: "SHUTDOOR", sounds: "plm_bang_dumpster plm_cabinet_shut plm_close_hatch plm_door_creakshut plm_door_latch plm_door_shut plm_door_slam" },
  { type: "TPLEVEL", sounds: "sum_bell_crystal" },
  { type: "BELL", sounds: "plm_jar_ding" },
  { type: "NOTHING_TO_OPEN", sounds: "plm_click_switch2 plm_door_knob" },
  { type: "LOCKPICK_FAIL", sounds: "plm_click_dry plm_click_switch plm_click_wood plm_door_echolock plm_door_wooden" },
  { type: "LOCKPICK", sounds: "plm_break_wood plm_cabinet_open plm_chest_unlatch plm_lock_case plm_lock_distant plm_open_case" },
  { type: "DISARM", sounds: "plm_bang_ceramic plm_chest_latch plm_click_switch3" },
  { type: "STAIRS_UP", sounds: "plm_floor_creak2" },
  { type: "STAIRS_DOWN", sounds: "plm_floor_creak" },
  { type: "ACT_ARTIFACT", sounds: "plm_aim_wand" },
  { type: "USE_STAFF", sounds: "plm_use_staff" },
  { type: "DESTROY", sounds: "plm_bang_metal plm_break_canister plm_break_glass plm_break_glass2 plm_break_plates plm_break_shatter plm_break_smash plm_glass_breaking plm_glass_break plm_glass_smashing" },
  { type: "WIELD", sounds: "plm_metal_sharpen" },
  { type: "QUIVER", sounds: "plc_miss_swish" },
  { type: "CURSED", sounds: "pls_man_oooh" },
  { type: "NOTICE", sounds: "id_bad_hmm" },
  { type: "RUNE", sounds: "id_good_hmm" },
  { type: "SPELL", sounds: "plm_spell1 plm_spell2 plm_spell3" },
  { type: "PRAYER", sounds: "sum_ainu_song" },
  { type: "FLEE", sounds: "mco_creature_yelp" },
  { type: "KILL", sounds: "mco_howl_croak mco_howl_deep mco_howl_distressed mco_howl_high mco_howl_long" },
  { type: "KILL_UNIQUE", sounds: "sum_ghost_wail" },
  { type: "KILL_KING", sounds: "amb_guitar_chord" },
  { type: "MON_HIT", sounds: "mco_hit_whip" },
  { type: "MON_TOUCH", sounds: "mco_click_vibra" },
  { type: "MON_PUNCH", sounds: "mco_squish_snap" },
  { type: "MON_KICK", sounds: "mco_rubber_thud" },
  { type: "MON_CLAW", sounds: "mco_ceramic_trill mco_scurry_dry" },
  { type: "MON_BITE", sounds: "mco_snarl_short mco_bite_soft mco_bite_munch mco_bite_long mco_bite_short mco_bite_gnash mco_bite_chomp mco_bite_regular mco_bite_small mco_bite_dainty mco_bite_hard mco_bite_chew" },
  { type: "MON_STING", sounds: "mco_castanet_trill mco_tube_hit" },
  { type: "MON_BUTT", sounds: "mco_cuica_rubbing mco_thud_crash" },
  { type: "MON_CRUSH", sounds: "mco_dino_low mco_squish_hit" },
  { type: "MON_ENGULF", sounds: "mco_dino_talk mco_dino_yawn" },
  { type: "MON_CRAWL", sounds: "mco_card_shuffle mco_shake_roll" },
  { type: "MON_DROOL", sounds: "mco_creature_choking mco_liquid_squirt" },
  { type: "MON_SPIT", sounds: "mco_attack_spray" },
  { type: "MON_GAZE", sounds: "mco_thoing_backwards" },
  { type: "MON_WAIL", sounds: "mco_dino_low" },
  { type: "MON_SPORE", sounds: "mco_dub_wobble mco_spray_long" },
  { type: "MON_BEG", sounds: "mco_man_mumble" },
  { type: "MON_INSULT", sounds: "mco_strange_thwoink" },
  { type: "MON_MOAN", sounds: "mco_strange_music" },
  { type: "SHRIEK", sounds: "mco_mouse_squeaks" },
  { type: "CREATE_TRAP", sounds: "mco_thoing_deep" },
  { type: "CAST_FEAR", sounds: "mco_creature_groan mco_dino_slur" },
  { type: "MULTIPLY", sounds: "mco_frog_trill" },
  { type: "SUM_MONSTER", sounds: "sum_chime_jangle" },
  { type: "SUM_AINU", sounds: "sum_ainu_song" },
  { type: "SUM_UNDEAD", sounds: "sum_ghost_oooo" },
  { type: "SUM_ANIMAL", sounds: "sum_lion_growl" },
  { type: "SUM_SPIDER", sounds: "sum_piano_scrape" },
  { type: "SUM_HOUND", sounds: "sum_lion_growl" },
  { type: "SUM_HYDRA", sounds: "sum_piano_scrape" },
  { type: "SUM_DEMON", sounds: "sum_ghost_wail sum_laugh_evil2" },
  { type: "SUM_DRAGON", sounds: "sum_piano_scrape" },
  { type: "SUM_HI_UNDEAD", sounds: "sum_ghost_moan" },
  { type: "SUM_HI_DRAGON", sounds: "sum_gong_temple" },
  { type: "SUM_HI_DEMON", sounds: "sum_ghost_moan" },
  { type: "SUM_WRAITH", sounds: "sum_bell_hand" },
  { type: "SUM_UNIQUE", sounds: "sum_bell_tone" },
  { type: "BR_FROST", sounds: "mco_attack_breath" },
  { type: "BR_ELEC", sounds: "mco_attack_breath" },
  { type: "BR_ACID", sounds: "mco_attack_breath" },
  { type: "BR_GAS", sounds: "mco_attack_breath" },
  { type: "BR_FIRE", sounds: "mco_attack_breath" },
  { type: "BR_DISEN", sounds: "mco_attack_breath" },
  { type: "BR_CHAOS", sounds: "mco_attack_breath" },
  { type: "BR_SHARDS", sounds: "mco_attack_breath" },
  { type: "BR_SOUND", sounds: "mco_attack_breath" },
  { type: "BR_LIGHT", sounds: "mco_attack_breath" },
  { type: "BR_DARK", sounds: "mco_attack_breath" },
  { type: "BR_NETHER", sounds: "mco_attack_breath" },
  { type: "BR_NEXUS", sounds: "mco_attack_breath" },
  { type: "BR_TIME", sounds: "mco_attack_breath" },
  { type: "BR_INERTIA", sounds: "mco_attack_breath" },
  { type: "BR_GRAVITY", sounds: "mco_attack_breath" },
  { type: "BR_PLASMA", sounds: "mco_attack_breath" },
  { type: "BR_FORCE", sounds: "mco_attack_breath" },
  { type: "BR_ELEMENTS", sounds: "mco_attack_breath" },
  { type: "IDENT_BAD", sounds: "id_bad_aww id_bad_dang id_bad_hmm id_bad_hmph id_bad_ohh" },
  { type: "IDENT_EGO", sounds: "id_ego_whoa id_ego_woohoo id_ego_yeah id_ego_yeah2 id_ego_yes" },
  { type: "IDENT_ART", sounds: "id_good_hey id_good_hey2 id_good_hmm id_good_huh id_good_ooh id_good_ooo id_good_wow" },
];
