/**
 * The loose-pack engine's own unit tests: manifest/family parsing, the slot
 * encoding, and how target rules become pref lines core's parser can resolve.
 *
 * The end-to-end proof that a converted pack draws the SAME pixels as the
 * tilesheet it came from is a separate file (linoleum-equivalence.test.ts);
 * this one pins the mechanics that proof depends on.
 */

import { afterEach, describe, expect, it } from "vitest";
import { LIGHTING, tileForFeature, tileForMonster } from "@neo-angband/core";
import type { TilePrefsDeps } from "@neo-angband/core";
import type { PoolDefinition, TargetRule } from "@neo-angband/linoleum/targets";
import {
  atlasToSlot,
  buildLinoleumIndex,
  LinoleumPack,
  LINOLEUM_MAX_SLOTS,
  linoleumPrefLines,
  loadLinoleumPack,
  parseFamiliesFile,
  parseLinoleumManifest,
  slotToAtlas,
} from "./linoleum-pack";
import { urlBaseResolver } from "./pack-files";
import type { PackFileResolver } from "./pack-files";
import { isTile, tileCode } from "./tiles";

/**
 * Minimal stand-ins for the registries: enough for the pref parser to resolve
 * the handful of selectors these tests use. The real registries are exercised
 * by the equivalence test.
 */
const FLOOR_FIDX = 3;
const MAGGOT_RIDX = 7;
const deps = {
  features: {
    lookupByCode: (code: string) => (code === "FLOOR" ? { fidx: FLOOR_FIDX } : null),
    lookupByName: () => null,
  },
  objects: { kinds: [], flavors: [], lookupSval: () => -1, lookupKind: () => null },
  monsters: {
    raceByName: (name: string) => (name === "Farmer Maggot" ? { ridx: MAGGOT_RIDX } : null),
  },
  traps: null,
} as unknown as TilePrefsDeps;

function rule(
  type: string,
  selector: string,
  kind: TargetRule["kind"],
  value: string,
): TargetRule {
  return { type, selector, kind, value };
}

describe("parseLinoleumManifest", () => {
  const text = [
    "# Generated by @neo-angband/linoleum",
    "pack:linoleum-original-tiles:Original Tiles (Linoleum)",
    "format:png",
    "resolution:8",
    "map:targets:maps/targets.txt",
    "map:families:maps/families.txt",
    "",
  ].join("\n");

  it("reads the pack line, format, resolution and map paths", () => {
    const manifest = parseLinoleumManifest(text);
    expect(manifest).not.toBeNull();
    expect(manifest?.packId).toBe("linoleum-original-tiles");
    expect(manifest?.displayName).toBe("Original Tiles (Linoleum)");
    expect(manifest?.format).toBe("png");
    expect(manifest?.resolution).toBe(8);
    expect(manifest?.maps.get("targets")).toBe("maps/targets.txt");
    expect(manifest?.maps.get("families")).toBe("maps/families.txt");
    expect(manifest?.maps.get("pools")).toBeUndefined();
  });

  it("keeps colons inside a display name", () => {
    expect(parseLinoleumManifest("pack:x:Tiles: the sequel\nresolution:16")?.displayName).toBe(
      "Tiles: the sequel",
    );
  });

  it("is null without a pack id or without a resolution", () => {
    expect(parseLinoleumManifest("format:png\nresolution:8")).toBeNull();
    expect(parseLinoleumManifest("pack:x:X\nformat:png")).toBeNull();
    expect(parseLinoleumManifest("pack:x:X\nresolution:0")).toBeNull();
    expect(parseLinoleumManifest("")).toBeNull();
  });
});

describe("parseFamiliesFile", () => {
  it("keeps the base asset and ignores the effect metadata", () => {
    const families = parseFamiliesFile(
      [
        "# header",
        "family:feat_more_lit_0_fx:selection:stable",
        "family:feat_more_lit_0_fx:asset:feat_more_lit_0",
        "family:feat_more_lit_0_fx:glow-alpha:0.35",
        "family:feat_more_lit_0_fx:tint:#ffcc66",
        "family:feat_more_lit_0_fx:pulse:slow",
        "family::asset:orphan",
        "not a family line",
      ].join("\n"),
    );
    expect(families.size).toBe(1);
    expect(families.get("feat_more_lit_0_fx")).toBe("feat_more_lit_0");
  });
});

describe("slot encoding", () => {
  it("round-trips every corner of the slot space through a tile code", () => {
    for (const slot of [0, 1, 127, 128, 129, 8191, LINOLEUM_MAX_SLOTS - 1]) {
      const { attr, char } = slotToAtlas(slot);
      expect(isTile(attr, char), `slot ${slot} must look like a tile`).toBe(true);
      expect(atlasToSlot(tileCode(attr, char))).toBe(slot);
    }
  });

  it("sets both high bits so the render treats a slot as a tile, not a glyph", () => {
    const { attr, char } = slotToAtlas(0);
    expect(attr & 0x80).toBe(0x80);
    expect(char & 0x80).toBe(0x80);
  });
});

describe("linoleumPrefLines", () => {
  it("turns an asset rule into the pref line the selector came from", () => {
    const out = linoleumPrefLines({
      rules: [rule("monster", "Farmer Maggot", "asset", "monster_farmer_maggot_0")],
    });
    expect(out.lines).toEqual(["monster:Farmer Maggot:0x80:0x80"]);
    expect(out.slots).toEqual([{ kind: "asset", asset: "monster_farmer_maggot_0" }]);
  });

  it("gives one slot to an asset used by several rules", () => {
    const out = linoleumPrefLines({
      rules: [
        rule("feat", "FLOOR", "asset", "shared"),
        rule("feat", "FLOOR:lit", "asset", "shared"),
        rule("monster", "Farmer Maggot", "asset", "other"),
      ],
    });
    expect(out.slots).toHaveLength(2);
    expect(out.lines).toEqual([
      "feat:FLOOR:*:0x80:0x80",
      "feat:FLOOR:lit:0x80:0x80",
      "monster:Farmer Maggot:0x80:0x81",
    ]);
  });

  it("spells an unsuffixed feat/trap selector as the `*` lighting wildcard", () => {
    // The converter's compatibility aliases have no :<variant>, and a 4-field
    // feat line would be rejected by the pref grammar (ui-prefs.c wants the
    // lighting token), so the alias has to say "every variant" explicitly.
    const out = linoleumPrefLines({
      rules: [
        rule("feat", "FLOOR", "asset", "a"),
        rule("trap", "pit", "asset", "b"),
        rule("feat", "FLOOR:dark", "asset", "c"),
        rule("monster", "Farmer Maggot", "asset", "d"),
        rule("GF", "ELEC:0", "asset", "e"),
      ],
    });
    expect(out.lines[0]).toBe("feat:FLOOR:*:0x80:0x80");
    expect(out.lines[1]).toBe("trap:pit:*:0x80:0x81");
    expect(out.lines[2]).toBe("feat:FLOOR:dark:0x80:0x82");
    expect(out.lines[3]).toBe("monster:Farmer Maggot:0x80:0x83");
    // Not a feat/trap: the selector's colons are its own, left alone.
    expect(out.lines[4]).toBe("GF:ELEC:0:0x80:0x84");
  });

  it("draws a family as its base asset and counts an undefined one", () => {
    const out = linoleumPrefLines({
      rules: [
        rule("feat", "MORE:lit", "family", "feat_more_lit_0_fx"),
        rule("feat", "LESS:lit", "family", "missing_fx"),
      ],
      families: new Map([["feat_more_lit_0_fx", "feat_more_lit_0"]]),
    });
    expect(out.slots).toEqual([{ kind: "asset", asset: "feat_more_lit_0" }]);
    expect(out.lines).toEqual(["feat:MORE:lit:0x80:0x80"]);
    expect(out.skipped.unresolved).toBe(1);
  });

  it("keeps a pool as a pool, and skips one that is empty or undefined", () => {
    const pool: PoolDefinition = {
      poolId: "floors",
      selection: "stable",
      members: ["a", "b", "c"],
    };
    const out = linoleumPrefLines({
      rules: [
        rule("feat", "FLOOR:lit", "pool", "floors"),
        rule("feat", "FLOOR:dark", "pool", "empty"),
        rule("feat", "FLOOR:los", "pool", "nope"),
      ],
      pools: [pool, { poolId: "empty", selection: "index", members: [] }],
    });
    expect(out.slots).toEqual([{ kind: "pool", pool }]);
    expect(out.lines).toEqual(["feat:FLOOR:lit:0x80:0x80"]);
    expect(out.skipped.unresolved).toBe(2);
  });

  it("skips a conditional rule instead of applying it unconditionally", () => {
    const out = linoleumPrefLines({
      rules: [
        rule("monster", "<player>:when:[EQU $CLASS Mage]", "asset", "player_mage"),
        rule("monster", "Farmer Maggot", "asset", "maggot"),
      ],
    });
    expect(out.skipped.conditional).toBe(1);
    expect(out.lines).toEqual(["monster:Farmer Maggot:0x80:0x80"]);
  });

  it("stops allocating past the slot space but keeps what fits", () => {
    const rules: TargetRule[] = [];
    for (let i = 0; i <= LINOLEUM_MAX_SLOTS; i++) {
      rules.push(rule("monster", `mon ${i}`, "asset", `asset_${i}`));
    }
    const out = linoleumPrefLines({ rules });
    expect(out.slots).toHaveLength(LINOLEUM_MAX_SLOTS);
    expect(out.lines).toHaveLength(LINOLEUM_MAX_SLOTS);
    expect(out.skipped.overflow).toBe(1);
  });
});

describe("buildLinoleumIndex", () => {
  it("resolves selectors through core's pref parser into a real TileMap", () => {
    const index = buildLinoleumIndex({
      rules: [
        rule("feat", "FLOOR", "asset", "floor_all"),
        rule("feat", "FLOOR:dark", "asset", "floor_dark"),
        rule("monster", "Farmer Maggot", "asset", "maggot"),
        rule("monster", "No Such Monster", "asset", "ghost"),
      ],
      deps,
    });

    const dark = tileForFeature(index.map, FLOOR_FIDX, LIGHTING.DARK);
    const lit = tileForFeature(index.map, FLOOR_FIDX, LIGHTING.LIT);
    expect(dark).not.toBeNull();
    expect(lit).not.toBeNull();
    // The unsuffixed alias filled every lighting; the exact dark rule then
    // overrode that one variant - the pref file's own last-wins layering.
    expect(index.slots[atlasToSlot(tileCode(lit!.attr, lit!.char))]).toEqual({
      kind: "asset",
      asset: "floor_all",
    });
    expect(index.slots[atlasToSlot(tileCode(dark!.attr, dark!.char))]).toEqual({
      kind: "asset",
      asset: "floor_dark",
    });

    const maggot = tileForMonster(index.map, MAGGOT_RIDX);
    expect(maggot).not.toBeNull();
    expect(index.slots[atlasToSlot(tileCode(maggot!.attr, maggot!.char))]).toEqual({
      kind: "asset",
      asset: "maggot",
    });
    // A selector no registry knows resolves to nothing and draws ASCII; it
    // still costs a slot (the rule was well-formed), which is harmless.
    expect(index.skipped).toEqual({ conditional: 0, unresolved: 0, overflow: 0 });
  });
});

describe("LinoleumPack", () => {
  const pack = (pool: PoolDefinition): LinoleumPack =>
    new LinoleumPack({
      menuname: "Test pack",
      resolve: urlBaseResolver("mods/test/pack"),
      manifest: {
        packId: "test",
        displayName: "Test pack",
        format: "png",
        resolution: 8,
        maps: new Map([["targets", "maps/targets.txt"]]),
      },
      index: buildLinoleumIndex({
        rules: [rule("feat", "FLOOR:lit", "pool", pool.poolId)],
        pools: [pool],
        deps,
      }),
    });

  const pool: PoolDefinition = {
    poolId: "floors",
    selection: "stable",
    members: ["floor_a", "floor_b", "floor_c"],
  };

  it("resolves a pool to one member, the same one for a given grid every time", () => {
    const p = pack(pool);
    const first = p.assetFor(0, { x: 12, y: 34 });
    expect(pool.members).toContain(first);
    expect(p.assetFor(0, { x: 12, y: 34 })).toBe(first);
    expect(p.assetFor(0, { x: 12, y: 34 })).toBe(first);
  });

  it("spreads a pool across the map instead of drawing one member everywhere", () => {
    const p = pack(pool);
    const seen = new Set<string>();
    for (let y = 0; y < 12; y++) {
      for (let x = 0; x < 12; x++) {
        const asset = p.assetFor(0, { x, y });
        expect(pool.members).toContain(asset);
        if (asset !== null) seen.add(asset);
      }
    }
    expect(seen.size).toBeGreaterThan(1);
  });

  it("has no asset for a slot it does not have", () => {
    expect(pack(pool).assetFor(99, { x: 0, y: 0 })).toBeNull();
  });

  it("degrades to ASCII (never throws) when there is no DOM to load images with", () => {
    // Host-agnostic by construction: no Image constructor here, so the asset
    // never loads and every blit declines instead of failing.
    const p = pack(pool);
    const ctx = {
      drawImage: () => {
        throw new Error("should not be reached");
      },
    } as unknown as CanvasRenderingContext2D;
    expect(p.drawTile(ctx, 0, 0, 8, 8, { row: 0, col: 0 }, { x: 1, y: 1 })).toBe(false);
    expect(p.ready).toBe(true);
    expect(p.loadedAssets).toBe(0);
  });
});

describe("loadLinoleumPack", () => {
  /** A pack served out of a plain map of URL -> text, no network. */
  function serve(files: Record<string, string>): typeof fetch {
    return ((url: string) => {
      const body = files[url];
      return Promise.resolve({
        ok: body !== undefined,
        text: () => Promise.resolve(body ?? ""),
      } as Response);
    }) as typeof fetch;
  }

  const files = {
    "mods/p/manifest.txt": [
      "pack:p:Pack P",
      "format:png",
      "resolution:8",
      "map:targets:maps/targets.txt",
      "map:pools:maps/pools.txt",
      "map:families:maps/families.txt",
    ].join("\n"),
    "mods/p/maps/targets.txt": [
      "target:feat:FLOOR:lit:pool:floors",
      "target:feat:FLOOR:dark:family:dark_fx",
      "target:monster:Farmer Maggot:asset:maggot",
    ].join("\n"),
    "mods/p/maps/pools.txt": [
      "pool:floors:selection:index",
      "pool:floors:member:floor_a",
      "pool:floors:member:floor_b",
    ].join("\n"),
    "mods/p/maps/families.txt": "family:dark_fx:asset:floor_dark",
  };

  const original = globalThis.fetch;
  afterEach(() => {
    globalThis.fetch = original;
  });

  it("reads the manifest, then every map it names, into one index", async () => {
    globalThis.fetch = serve(files);
    const pack = await loadLinoleumPack({ resolve: urlBaseResolver("mods/p"), menuname: "Pack P", deps });
    expect(pack).not.toBeNull();
    expect(pack?.manifest.resolution).toBe(8);
    expect(pack?.menuname).toBe("Pack P");
    // One slot per distinct mapping: the pool, the family's asset, the asset.
    expect(pack?.index.slots).toHaveLength(3);
    expect(pack?.index.slots.some((s) => s.kind === "pool")).toBe(true);
    expect(pack?.index.slots).toContainEqual({ kind: "asset", asset: "floor_dark" });
    expect(pack?.index.slots).toContainEqual({ kind: "asset", asset: "maggot" });
    // The pool's own selection rule survived the round trip through pools.txt.
    const pool = pack?.index.slots.find((s) => s.kind === "pool");
    expect(pool?.kind === "pool" && pool.pool.selection).toBe("index");
  });

  it("is null when the pack is not there, so the game just stays ASCII", async () => {
    globalThis.fetch = serve({});
    expect(await loadLinoleumPack({ resolve: urlBaseResolver("mods/p"), menuname: "Pack P", deps })).toBeNull();
  });

  it("is null when the manifest names no target map", async () => {
    globalThis.fetch = serve({
      "mods/p/manifest.txt": "pack:p:Pack P\nresolution:8",
    });
    expect(await loadLinoleumPack({ resolve: urlBaseResolver("mods/p"), menuname: "Pack P", deps })).toBeNull();
  });

  /**
   * The seam that lets a pack come from somewhere with no site path: a mod the
   * player picked, or one installed from GitHub and kept in IndexedDB. Its files
   * are reached through the mod's own assetUrl, which hands back `blob:` URLs
   * that have no relationship to the pack's directory layout - so if the loader
   * built any path itself, this pack would not load.
   */
  it("loads a pack whose files have no site path at all (an installed mod)", async () => {
    const blobs = new Map<string, string>();
    const bodies: Record<string, string> = {};
    let n = 0;
    for (const [path, text] of Object.entries(files)) {
      const rel = path.slice("mods/p/".length);
      const url = `blob:neo/${(n += 1)}`;
      blobs.set(rel, url);
      bodies[url] = text;
    }
    globalThis.fetch = serve(bodies);
    const resolve: PackFileResolver = (rel) => Promise.resolve(blobs.get(rel) ?? null);

    const pack = await loadLinoleumPack({ resolve, menuname: "Pack P", deps });
    expect(pack?.index.slots).toHaveLength(3);
    expect(pack?.index.slots).toContainEqual({ kind: "asset", asset: "maggot" });
  });

  it("is null when the resolver refuses the manifest, and never throws when it does", async () => {
    globalThis.fetch = serve({});
    expect(
      await loadLinoleumPack({ resolve: () => Promise.resolve(null), menuname: "P", deps }),
    ).toBeNull();
    expect(
      await loadLinoleumPack({
        resolve: () => Promise.reject(new Error("storage gone")),
        menuname: "P",
        deps,
      }),
    ).toBeNull();
  });

  it("tolerates a missing pools/families file rather than failing the pack", async () => {
    globalThis.fetch = serve({
      "mods/p/manifest.txt": files["mods/p/manifest.txt"],
      "mods/p/maps/targets.txt": files["mods/p/maps/targets.txt"],
    });
    const pack = await loadLinoleumPack({ resolve: urlBaseResolver("mods/p"), menuname: "Pack P", deps });
    // The plain asset rule still works; the pool and family rules are dropped.
    expect(pack?.index.slots).toEqual([{ kind: "asset", asset: "maggot" }]);
    expect(pack?.index.skipped.unresolved).toBe(2);
  });
});
