/**
 * Monte-Carlo statistics harness - the port's answer to upstream's
 * main-stats.c (reference/src/main-stats.c).
 *
 * main-stats births one wizard-mode character per run and descends level by
 * level 1..100 (descend_dungeon, main-stats.c L665-698), accumulating per-level
 * metrics across many runs: monsters by race (kill_all_monsters L533-550, the
 * `level_data[level].monsters[ridx]++` at L543), the level's object/monster
 * FEELINGs (L688-692), gold by origin (log_all_objects L624-626) and the item
 * allocation by origin (artifacts / wearables / consumables, L628-657). It then
 * writes the aggregate to a SQLite database.
 *
 * This port mirrors the metrics but not the transport: it drives the port's
 * REAL generation + allocation code (generateLevel, the same call bootLevel and
 * the live game's changeLevel make) headlessly and emits a plain-JSON aggregate
 * instead of SQLite. Two deliberate, documented deviations from main-stats:
 *
 *  - We read the freshly generated level directly (g.monsters, g.objects,
 *    g.c.feeling) instead of birthing a player and killing every monster; the
 *    generation + allocation RNG is identical, so the distributions are the
 *    port's true generator output. Monster-held objects are still swept, as
 *    log_all_objects does (L604-609).
 *  - Each (run, depth) cell draws from a seed derived from the base seed
 *    (deriveSeed below) rather than one continuous descending stream. This is
 *    the decision-22 guarantee ("the engine is a function of the seed") applied
 *    for CI stability: the whole batch is reproducible to the exact integer,
 *    and a single flaky cell cannot shift every deeper level.
 *
 * Determinism: NO wall-clock, NO Math.random. Every draw traces to baseSeed.
 *
 * Relationship to wiz-stats.c (the in-game statistics collector behind the
 * do_cmd_wiz_collect_* commands): main-stats.c and wiz-stats.c are two
 * implementations of the same Monte-Carlo concept - main-stats.c is the
 * standalone headless tool (SQLite output), wiz-stats.c is the in-game version
 * (text log). This module tracks main-stats.c, the natural oracle for a
 * headless TS harness. The wiz-stats.c-only surfaces (the diving / clearing
 * object+monster collector, pit_stats, disconnect_stats) are ported alongside
 * it in wiz-stats.ts, reusing this module's collectLevel / DepthMetrics so the
 * object+monster tallies stay defined in exactly one place.
 */

import {
  ArtifactState,
  ENGINE_VERSION,
  ORIGIN,
  ORIGIN_ENTRIES,
  PARITY_BASELINE,
  RANDNAME_TOLKIEN,
  Rng,
  TV,
  TVAL_ENTRIES,
  bindCore,
  doRandart,
  generateLevel,
  genDeps,
} from "@neo-angband/core";
import type { CoreRegistries, GameObject, GamePack } from "@neo-angband/core";

/** Parameters for a stats batch. Sane defaults let `runStatsBatch(pack)` work. */
export interface StatsParams {
  /** Number of full descents to aggregate (main-stats -n). Default 5. */
  runs: number;
  /** Shallowest depth to generate (inclusive). Default 1. */
  depthMin: number;
  /** Deepest depth to generate (inclusive). Default 10. */
  depthMax: number;
  /** Base seed every per-cell seed is derived from. Default 1. */
  baseSeed: number;
  /** Player race name recorded in meta (inert for generation). Default first. */
  race: string;
  /** Player class name recorded in meta (inert for generation). Default first. */
  class: string;
  /** OPT(player, birth_randarts): swap in a random artifact set per run. */
  randarts: boolean;
}

/** Per-depth aggregate, accumulated across every run that reached this depth. */
export interface DepthMetrics {
  /** How many generated levels contributed (== runs, unless a depth failed). */
  levels: number;
  /** Total monsters placed across all contributing levels. */
  monsterTotal: number;
  /** Monster count keyed by race index (ridx); mirrors L543. */
  monsters: Record<string, number>;
  /** Total object entries swept (floor + monster-held). */
  objectTotal: number;
  /** Object-entry count keyed by tval. */
  objectsByTval: Record<string, number>;
  /** Object-entry count keyed by kind index (kidx) - cheap and high-signal. */
  objectsByKind: Record<string, number>;
  /** Artifact object entries (obj.artifact set); mirrors L628-630. */
  artifacts: number;
  /** Total gold (sum of gold-object pval); mirrors L624-626. */
  gold: number;
  /** Gold total keyed by origin. */
  goldByOrigin: Record<string, number>;
  /** Object-feeling digit histogram (feeling/10), 0..10; mirrors L689/L691. */
  objFeeling: Record<string, number>;
  /** Monster-feeling digit histogram (feeling%10), 0..9; mirrors L690/L692. */
  monFeeling: Record<string, number>;
}

/** A full stats report: reproducible metric -> depth -> aggregate. */
export interface StatsReport {
  meta: {
    engineVersion: string;
    parityBaseline: string;
    /**
     * "port" == generated by this TS harness (a self-consistency / regression
     * baseline). A future cross-implementation baseline produced by the C
     * main-stats tool would carry "c-main-stats"; the comparator keys off
     * nothing here, so either can be diffed against the other.
     */
    generatedBy: "port" | "c-main-stats";
    runs: number;
    depthMin: number;
    depthMax: number;
    baseSeed: number;
    race: string;
    class: string;
    randarts: boolean;
    note: string;
  };
  depths: Record<string, DepthMetrics>;
}

/** The default batch: small enough to run in CI, wide enough to have signal. */
export const DEFAULT_STATS_PARAMS: StatsParams = {
  runs: 5,
  depthMin: 1,
  depthMax: 10,
  baseSeed: 1,
  race: "Human",
  class: "Warrior",
  randarts: false,
};

/**
 * The pinned parameters the committed baseline is captured with and the parity
 * test re-runs. Kept small so the vitest guard stays fast (24 level builds) but
 * spanning several depths for real signal. Changing these REQUIRES regenerating
 * the baseline (pnpm --filter @neo-angband/cli stats:baseline).
 */
export const BASELINE_PARAMS: StatsParams = {
  runs: 3,
  depthMin: 1,
  depthMax: 8,
  baseSeed: 1337,
  race: "Human",
  class: "Warrior",
  randarts: false,
};

/** Honest one-liner stamped into every port-generated report. */
const PORT_BASELINE_NOTE =
  "Generated by the TS port itself: a self-consistency/regression guard, " +
  "NOT a C-vs-TS distribution diff. See packages/cli/baseline/README for how " +
  "to produce a C main-stats baseline and upgrade this to a true parity check.";

/**
 * Derive a reproducible uint32 seed for one (run, depth) cell from the base
 * seed. A splitmix/murmur-style finalizing mix over the three inputs so
 * adjacent cells (run+1, depth+1) land far apart in the stream. Pure integer
 * math in C uint32 semantics (Math.imul + >>> 0); no wall-clock, no global RNG.
 */
export function deriveSeed(baseSeed: number, run: number, depth: number): number {
  let h = baseSeed >>> 0;
  h = Math.imul(h ^ ((run + 0x9e3779b9) >>> 0), 0x85ebca6b) >>> 0;
  h = Math.imul(h ^ ((depth + 0x165667b1) >>> 0), 0xc2b2ae35) >>> 0;
  h ^= h >>> 13;
  h = Math.imul(h, 0x27d4eb2f) >>> 0;
  h ^= h >>> 16;
  return h >>> 0;
}

/** A distinct salt so the per-run randart seed never collides with a level. */
function deriveRandartSeed(baseSeed: number, run: number): number {
  return deriveSeed(baseSeed ^ 0x5a5a5a5a, run, 0x7fffffff) % 0x10000000;
}

function bump(rec: Record<string, number>, key: number, by = 1): void {
  const k = String(key);
  rec[k] = (rec[k] ?? 0) + by;
}

/** Fresh, all-zero per-depth aggregate. */
export function emptyDepth(): DepthMetrics {
  return {
    levels: 0,
    monsterTotal: 0,
    monsters: {},
    objectTotal: 0,
    objectsByTval: {},
    objectsByKind: {},
    artifacts: 0,
    gold: 0,
    goldByOrigin: {},
    objFeeling: {},
    monFeeling: {},
  };
}

/**
 * swap_randart_set (game.ts): replace the registry's artifact set with a
 * random one drawn from `seed`, threading the Tolkien name corpus so the RNG
 * draw count matches upstream. Kept local (the core helper is not exported).
 */
function applyRandarts(reg: CoreRegistries, seed: number): void {
  const set = doRandart(reg.objects, seed, reg.nameSections.get(RANDNAME_TOLKIEN));
  reg.objects.artifacts.length = 0;
  reg.objects.artifacts.push(...set);
}

/**
 * Fold one generated level into its depth aggregate. Mirrors the collection
 * pass in main-stats' descend_dungeon (feelings) + log_all_objects (objects)
 * + kill_all_monsters (monsters). Objects with origin >= ORIGIN_STATS are
 * skipped exactly as log_all_objects L619 skips them (they are never naturally
 * generated - stores, birth kit, cheat).
 */
export function collectLevel(
  m: DepthMetrics,
  g: ReturnType<typeof generateLevel>,
): void {
  m.levels += 1;

  /* Level feelings (main-stats L688-692): feeling = objDigit*10 + monDigit. */
  const feeling = g.c.feeling;
  const objF = Math.trunc(feeling / 10);
  const monF = feeling - 10 * objF;
  bump(m.objFeeling, Math.min(objF, 10));
  bump(m.monFeeling, Math.min(monF, 9));

  /* Monsters by race (kill_all_monsters L543). */
  for (const pm of g.monsters) {
    bump(m.monsters, pm.mon.race.ridx);
    m.monsterTotal += 1;
  }

  /* Floor objects + monster-held objects (log_all_objects L587-660). */
  const sweep = (objs: readonly GameObject[]): void => {
    for (const obj of objs) {
      if (obj.origin >= ORIGIN.STATS) continue; // L619
      if (obj.tval === TV.GOLD) {
        /* tval_is_money: accumulate the amount by origin (L624-626). */
        m.gold += obj.pval;
        bump(m.goldByOrigin, obj.origin, obj.pval);
        continue;
      }
      m.objectTotal += 1;
      bump(m.objectsByTval, obj.tval);
      bump(m.objectsByKind, obj.kind.kidx);
      if (obj.artifact) m.artifacts += 1; // L628-630
    }
  };
  sweep(g.objects.map((po) => po.obj));
  for (const pm of g.monsters) sweep(pm.mon.heldObj);
}

/**
 * Run a full Monte-Carlo batch and return the aggregate report.
 *
 * Per run: rebind the registries fresh (a fresh character's world - resets
 * unique max_num and the created-artifact marks, mirroring main-stats'
 * unkill_uniques + reset_artifacts at L790-791), optionally swap in a randart
 * set, then generate every depth in range sharing that run's registries and
 * ArtifactState so an artifact found shallow is not re-found deep within the
 * same descent (main-stats does not reset between levels of a run).
 */
export function runStatsBatch(
  pack: GamePack,
  params: Partial<StatsParams> = {},
): StatsReport {
  const p: StatsParams = { ...DEFAULT_STATS_PARAMS, ...params };
  if (p.depthMax < p.depthMin) {
    throw new RangeError(`depthMax (${p.depthMax}) < depthMin (${p.depthMin})`);
  }

  const depths: Record<string, DepthMetrics> = {};
  for (let d = p.depthMin; d <= p.depthMax; d++) depths[String(d)] = emptyDepth();

  for (let run = 0; run < p.runs; run++) {
    const reg = bindCore(pack);
    if (p.randarts) applyRandarts(reg, deriveRandartSeed(p.baseSeed, run));
    const artifacts = new ArtifactState(reg.objects.artifacts.length);

    for (let d = p.depthMin; d <= p.depthMax; d++) {
      const rng = new Rng(deriveSeed(p.baseSeed, run, d));
      const deps = genDeps(reg, true, artifacts, false);
      const g = generateLevel(rng, d, deps, { daytime: true });
      collectLevel(depths[String(d)]!, g);
    }
  }

  return {
    meta: {
      engineVersion: ENGINE_VERSION,
      parityBaseline: PARITY_BASELINE,
      generatedBy: "port",
      runs: p.runs,
      depthMin: p.depthMin,
      depthMax: p.depthMax,
      baseSeed: p.baseSeed,
      race: p.race,
      class: p.class,
      randarts: p.randarts,
      note: PORT_BASELINE_NOTE,
    },
    depths,
  };
}

/**
 * Serialize a report with sorted keys at every level so a committed baseline
 * (and any diff against it) is byte-stable regardless of insertion order.
 */
export function serializeReport(report: StatsReport): string {
  return JSON.stringify(report, sortedReplacer, 2) + "\n";
}

/** JSON.stringify replacer that emits object keys in a stable sorted order. */
function sortedReplacer(_key: string, value: unknown): unknown {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    const src = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(src).sort(numericAwareCompare)) out[k] = src[k];
    return out;
  }
  return value;
}

/** Sort numeric-looking keys numerically ("2" before "10"), else lexically. */
function numericAwareCompare(a: string, b: string): number {
  const na = Number(a);
  const nb = Number(b);
  if (!Number.isNaN(na) && !Number.isNaN(nb)) return na - nb;
  return a < b ? -1 : a > b ? 1 : 0;
}

/** Human-readable one-line-per-depth summary for the terminal. */
export function summarizeReport(report: StatsReport): string {
  const lines: string[] = [];
  const { meta } = report;
  lines.push(
    `stats: engine ${meta.engineVersion} (parity ${meta.parityBaseline}) ` +
      `runs=${meta.runs} depths=${meta.depthMin}..${meta.depthMax} ` +
      `seed=${meta.baseSeed} randarts=${meta.randarts}`,
  );
  lines.push(
    "depth  levels  mons  objs  arts  gold      objFeel  monFeel",
  );
  for (const key of Object.keys(report.depths).sort(numericAwareCompare)) {
    const d = report.depths[key]!;
    const objF = topKey(d.objFeeling);
    const monF = topKey(d.monFeeling);
    lines.push(
      `${key.padStart(5)}  ${String(d.levels).padStart(6)}  ` +
        `${String(d.monsterTotal).padStart(4)}  ${String(d.objectTotal).padStart(4)}  ` +
        `${String(d.artifacts).padStart(4)}  ${String(d.gold).padStart(8)}  ` +
        `${objF.padStart(7)}  ${monF.padStart(7)}`,
    );
  }
  return lines.join("\n");
}

/** The most common key in a histogram (for the summary table), or "-". */
function topKey(rec: Record<string, number>): string {
  let best: string | null = null;
  let bestN = -1;
  for (const [k, n] of Object.entries(rec)) {
    if (n > bestN) {
      bestN = n;
      best = k;
    }
  }
  return best ?? "-";
}

/** Origin-index -> name, for anyone inspecting goldByOrigin keys. */
export function originName(origin: number): string {
  return ORIGIN_ENTRIES[origin]?.name ?? String(origin);
}

/** tval -> name, for anyone inspecting objectsByTval keys. */
export function tvalName(tval: number): string {
  return TVAL_ENTRIES[tval]?.name ?? String(tval);
}
