/**
 * Browser-safe planning half of the Linoleum tilesheet converter.
 *
 * The Node exporter in convert.ts owns filesystem access and PNG encoding.  This
 * module owns the conversion decisions: which source rectangle backs each
 * selector, the generated maps, and the deterministic file names.  Keeping that
 * work free of node:fs and pngjs lets the web shell crop the very same plan the
 * offline exporter uses after a player selects a pack.
 */

import { deterministicAssetName, selectorKey } from "./naming.js";
import { readLegacySelectors } from "./prf.js";
import type { PrefSource } from "./prf.js";
import type { PackConfig } from "./packs.js";
import { formatPoolLines, formatTargetRule } from "./targets.js";
import type { PoolDefinition, TargetRule } from "./targets.js";

export const GENERATED_BY = "# Generated by @rpgm-tools/neo-angband-linoleum";

export interface PackAuthoring {
  pools?: readonly PoolDefinition[];
  targets?: readonly TargetRule[];
}

export interface ExportEntry {
  type: string;
  selectorValue: string;
  compatibilitySelectorValue: string;
  assetName: string;
  mappingKind: "asset" | "family";
  mappingValue: string;
  logicalValue: string;
  variant: string;
  condition: string | null;
  sourceLine: string;
  sourceFile: string;
  sourceOrder: number;
  row: number;
  column: number;
}

export interface EffectProfile {
  glowAlpha: number;
  tint: string;
  pulse: string;
}

export interface SourceTileRectangle {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface PlannedTileCrop {
  path: string;
  rect: SourceTileRectangle;
}

export interface LinoleumConversionPlan {
  /** Text files, keyed relative to the generated loose-pack root. */
  files: ReadonlyMap<string, string>;
  /** PNG crops, in source order. Repeated paths deliberately keep the last crop. */
  crops: readonly PlannedTileCrop[];
  assetCount: number;
  exactSelectorCount: number;
  compatibilityAliasCount: number;
  totalTargetRuleCount: number;
  tallAssetCount: number;
  invalidSourceSelectorCount: number;
}

interface EffectFamily {
  familyId: string;
  assetName: string;
  glowAlpha: number;
  tint: string;
  pulse: string;
}

const collator = new Intl.Collator("en-US", { sensitivity: "accent" });

function compareSourceOrder(a: ExportEntry, b: ExportEntry): number {
  return a.sourceOrder - b.sourceOrder;
}

function compareRuleOrder(a: ExportEntry, b: ExportEntry): number {
  const byType = collator.compare(a.type, b.type);
  return byType !== 0 ? byType : collator.compare(a.selectorValue, b.selectorValue);
}

function isNullOrWhitespace(value: string | null): boolean {
  return value === null || value.trim().length === 0;
}

export function compatibilityVariantRank(type: string, variant: string): number {
  const typeLower = type.toLowerCase();
  if (typeLower !== "feat" && typeLower !== "trap") return 0;
  switch (variant.toLowerCase()) {
    case "*": return 0;
    case "lit": return 1;
    case "torch": return 2;
    case "los": return 3;
    case "dark": return 4;
    default: return 5;
  }
}

export function sourceTileRectangle(
  column: number,
  row: number,
  tileWidth: number,
  tileHeight: number,
  overdrawRow: number,
  overdrawMax: number,
): SourceTileRectangle {
  let y = row * tileHeight;
  let height = tileHeight;
  if (overdrawRow > 0 && row >= overdrawRow && row <= overdrawMax) {
    y -= tileHeight;
    height += tileHeight;
  }
  return { x: column * tileWidth, y, width: tileWidth, height };
}

export function effectProfileFor(type: string, selectorValue: string): EffectProfile | null {
  if (type.toLowerCase() !== "feat") return null;
  if (/^LESS:(dark|lit|los|torch|\*)$/i.test(selectorValue)) {
    return { glowAlpha: 72, tint: "180,220,255,48", pulse: "168,255,1400" };
  }
  if (/^MORE:(dark|lit|los|torch|\*)$/i.test(selectorValue)) {
    return { glowAlpha: 64, tint: "255,210,150,40", pulse: "176,255,1200" };
  }
  return null;
}

export function selectCompatibilityEntry(entries: readonly ExportEntry[]): ExportEntry | null {
  if (entries.length === 0) return null;
  return [...entries].sort((a, b) => {
    const byCondition = Number(!isNullOrWhitespace(a.condition)) - Number(!isNullOrWhitespace(b.condition));
    if (byCondition !== 0) return byCondition;
    const byVariant = compatibilityVariantRank(a.type, a.variant) - compatibilityVariantRank(b.type, b.variant);
    return byVariant !== 0 ? byVariant : a.sourceOrder - b.sourceOrder;
  })[0] ?? null;
}

function addUnique(entries: ExportEntry[], seen: Set<string>, entry: ExportEntry): void {
  const key = selectorKey(entry.type, entry.selectorValue);
  if (seen.has(key)) return;
  entries.push(entry);
  seen.add(key);
}

/**
 * Plan one conversion without reading or writing bytes.  The caller supplies the
 * source image's dimensions and the already-read pref texts; Node then encodes
 * crops with pngjs while the browser uses Canvas.
 */
export function planTilesheetConversion(input: {
  pack: PackConfig;
  prefSources: readonly PrefSource[];
  sheetWidth: number;
  sheetHeight: number;
  authoring?: PackAuthoring;
}): LinoleumConversionPlan {
  const { pack } = input;
  const tileWidth = pack.tileWidth ?? pack.resolution;
  const tileHeight = pack.tileHeight ?? pack.resolution;
  if (input.sheetWidth < tileWidth || input.sheetHeight < tileHeight) {
    throw new Error(`Tileset image is smaller than the declared resolution for '${pack.key}'.`);
  }
  const overdrawRow = pack.overdrawRow ?? 0;
  const overdrawMax = pack.overdrawMax ?? 0;
  const authoringPools = input.authoring?.pools ?? [];
  const authoredTargets = input.authoring?.targets ?? [];
  const entries = readLegacySelectors(input.prefSources);
  const exact: ExportEntry[] = [];
  const exactSeen = new Set<string>();
  const compatibility: ExportEntry[] = [];
  const compatibilitySeen = new Set<string>();
  const exportable: ExportEntry[] = [];
  /** Names claimed even by an invalid source entry, matching the Node exporter. */
  const usedAssetNames = new Set<string>();
  /** Names whose source rectangle actually landed in the generated pack. */
  const uniqueAssets = new Set<string>();
  const assetNameBySelector = new Map<string, string>();
  const tallAssets = new Set<string>();
  const families = new Map<string, EffectFamily>();
  const crops: PlannedTileCrop[] = [];
  let invalidSourceSelectorCount = 0;

  const assetNameFor = (entry: (typeof entries)[number]): string => {
    const selector = selectorKey(entry.type, entry.exactSelectorValue);
    const existing = assetNameBySelector.get(selector);
    if (existing !== undefined) return existing;
    const base = deterministicAssetName(entry.type, entry.exactSelectorValue);
    let name = base;
    for (let n = 1; usedAssetNames.has(name); n += 1) name = base.replace(/_0$/, `_${n}`);
    usedAssetNames.add(name);
    assetNameBySelector.set(selector, name);
    return name;
  };

  for (const entry of entries) {
    const assetName = assetNameFor(entry);
    const rect = sourceTileRectangle(
      entry.column, entry.row, tileWidth, tileHeight, overdrawRow, overdrawMax,
    );
    if (rect.x < 0 || rect.y < 0 || rect.x + rect.width > input.sheetWidth || rect.y + rect.height > input.sheetHeight) {
      invalidSourceSelectorCount += 1;
      continue;
    }
    crops.push({ path: `images/${String(pack.resolution)}/${assetName}.png`, rect });
    const output: ExportEntry = {
      type: entry.type,
      selectorValue: entry.exactSelectorValue,
      compatibilitySelectorValue: entry.compatibilitySelectorValue,
      assetName,
      mappingKind: "asset",
      mappingValue: assetName,
      logicalValue: entry.logicalValue,
      variant: entry.variant,
      condition: entry.condition,
      sourceLine: entry.sourceLine,
      sourceFile: entry.sourceFile,
      sourceOrder: entry.sourceOrder,
      row: entry.row,
      column: entry.column,
    };
    const effect = effectProfileFor(output.type, output.selectorValue);
    if (effect !== null) {
      const familyId = `${assetName}_fx`;
      output.mappingKind = "family";
      output.mappingValue = familyId;
      families.set(familyId, { familyId, assetName, ...effect });
    }
    exportable.push(output);
    addUnique(exact, exactSeen, output);
    uniqueAssets.add(assetName);
    if (rect.height > tileHeight) tallAssets.add(assetName);
  }

  const groups = new Map<string, ExportEntry[]>();
  for (const entry of exportable) {
    const key = selectorKey(entry.type, entry.compatibilitySelectorValue);
    const group = groups.get(key);
    if (group) group.push(entry);
    else groups.set(key, [entry]);
  }
  for (const group of groups.values()) {
    const selected = selectCompatibilityEntry(group);
    if (selected === null || selected.selectorValue.toLowerCase() === selected.compatibilitySelectorValue.toLowerCase()) continue;
    addUnique(compatibility, compatibilitySeen, { ...selected, selectorValue: selected.compatibilitySelectorValue });
  }

  const poolIds = new Set(authoringPools.map((pool) => pool.poolId));
  for (const pool of authoringPools) {
    for (const member of pool.members) {
      if (!uniqueAssets.has(member)) throw new Error(`Pool '${pool.poolId}' references unknown asset '${member}' in pack '${pack.key}'.`);
    }
  }
  for (const target of authoredTargets) {
    if (target.kind === "pool" && !poolIds.has(target.value)) throw new Error(`Target '${target.type}:${target.selector}' references unknown pool '${target.value}' in pack '${pack.key}'.`);
    if (target.kind === "asset" && !uniqueAssets.has(target.value)) throw new Error(`Target '${target.type}:${target.selector}' references unknown asset '${target.value}' in pack '${pack.key}'.`);
  }

  const files = new Map<string, string>();
  const manifest = [
    `pack:${pack.packId}:${pack.displayName}`,
    "format:png",
    `resolution:${pack.resolution}`,
    "map:targets:maps/targets.txt",
  ];
  if (families.size > 0) manifest.push("map:families:maps/families.txt");
  if (authoringPools.length > 0) manifest.push("map:pools:maps/pools.txt");
  if (tallAssets.size > 0) manifest.push("map:tall:maps/tall.txt");
  files.set("manifest.txt", manifest.join("\n") + "\n");

  const targetLines = [
    GENERATED_BY,
    "# Compatibility aliases come first so current unsuffixed runtime lookups stay usable.",
    "",
    ...[...compatibility].sort(compareRuleOrder).map((entry) => `target:${entry.type}:${entry.selectorValue}:${entry.mappingKind}:${entry.mappingValue}`),
  ];
  if (compatibility.length > 0) targetLines.push("");
  targetLines.push("# Exact legacy selectors, in source order - a later rule overrides an earlier one.");
  targetLines.push(...[...exact].sort(compareSourceOrder).map((entry) => `target:${entry.type}:${entry.selectorValue}:${entry.mappingKind}:${entry.mappingValue}`));
  if (authoredTargets.length > 0) {
    targetLines.push("", "# Authored per-object and variant-pool rules (additive; see maps/pools.txt).");
    targetLines.push(...[...authoredTargets].sort((a, b) => {
      const byType = collator.compare(a.type, b.type);
      return byType !== 0 ? byType : collator.compare(a.selector, b.selector);
    }).map(formatTargetRule));
  }
  files.set("maps/targets.txt", targetLines.join("\n") + "\n");

  if (families.size > 0) {
    const lines = [GENERATED_BY, "# Family effect metadata stays behind stable target selector syntax.", ""];
    for (const family of [...families.values()].sort((a, b) => collator.compare(a.familyId, b.familyId))) {
      lines.push(
        `family:${family.familyId}:selection:stable`,
        `family:${family.familyId}:asset:${family.assetName}`,
        `family:${family.familyId}:glow-alpha:${family.glowAlpha}`,
        `family:${family.familyId}:tint:${family.tint}`,
        `family:${family.familyId}:pulse:${family.pulse}`,
        "",
      );
    }
    files.set("maps/families.txt", lines.join("\n") + "\n");
  }
  if (authoringPools.length > 0) {
    const lines = [GENERATED_BY, "# Variant pools: a selector may map to a pool of candidate assets that", "# a runtime resolves per grid (see docs/LINOLEUM.md, selectPoolMember).", ""];
    for (const pool of authoringPools) lines.push(...formatPoolLines(pool), "");
    files.set("maps/pools.txt", lines.join("\n") + "\n");
  }
  if (tallAssets.size > 0) {
    const lines = [
      GENERATED_BY,
      "# Double-height (overdraw) assets: each image is two cells tall and",
      "# BOTTOM-ANCHORED, so a runtime draws it over the cell above the one it",
      "# is placed in (is_dh_tile, grafmode.c L241; docs/LINOLEUM.md).",
      "",
      ...[...tallAssets].sort((a, b) => collator.compare(a, b)).map((asset) => `tall:${asset}`),
    ];
    files.set("maps/tall.txt", lines.join("\n") + "\n");
  }
  return {
    files,
    crops,
    assetCount: uniqueAssets.size,
    exactSelectorCount: exact.length,
    compatibilityAliasCount: compatibility.length,
    totalTargetRuleCount: exact.length + compatibility.length,
    tallAssetCount: tallAssets.size,
    invalidSourceSelectorCount,
  };
}
