/**
 * Linoleum loose-pack converter.
 *
 * Faithful port of the export half of Aaron's
 * scripts/build-linoleum-packs.ps1 (upstream fork), using pngjs instead of
 * System.Drawing for tile extraction. Intentional divergences are limited
 * to: generated-by header text naming this tool, LF line endings without a
 * BOM, and inventory reports written into the output root.
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, join } from "node:path";
import { PNG } from "pngjs";
import { deterministicAssetName, selectorKey } from "./naming.js";
import { readLegacySelectors } from "./prf.js";
import type { PrefSource } from "./prf.js";
import { selectPacks } from "./packs.js";
import type { PackConfig } from "./packs.js";

/** Header comment naming this tool; the only allowed textual divergence. */
const GENERATED_BY = "# Generated by @neo-angband/linoleum";

/** One exportable target rule (exact or compatibility alias). */
export interface ExportEntry {
  type: string;
  selectorValue: string;
  compatibilitySelectorValue: string;
  assetName: string;
  mappingKind: "asset" | "family";
  mappingValue: string;
  logicalValue: string;
  variant: string;
  condition: string | null;
  sourceLine: string;
  sourceFile: string;
  sourceOrder: number;
  row: number;
  column: number;
}

/** Family effect constants for feat LESS:/MORE: selectors. */
export interface EffectProfile {
  glowAlpha: number;
  tint: string;
  pulse: string;
}

interface EffectFamily {
  familyId: string;
  assetName: string;
  glowAlpha: number;
  tint: string;
  pulse: string;
}

/** Per-pack conversion result, mirroring the ps1 result object. */
export interface PackResult {
  key: string;
  displayName: string;
  sourceMode: string;
  sourceDirectory: string;
  resolution: number;
  packRoot: string;
  manifestPath: string;
  targetMapPath: string;
  familyMapPath: string;
  prefFiles: readonly string[];
  prefMirrorPaths: Record<string, string>;
  legacyTypeCounts: Record<string, number>;
  exactTypeCounts: Record<string, number>;
  compatibilityAliasCounts: Record<string, number>;
  exactSelectorCount: number;
  compatibilityAliasCount: number;
  totalTargetRuleCount: number;
  assetCount: number;
  statefulSelectorCount: number;
  conditionalSelectorCount: number;
  invalidSourceSelectorCount: number;
  invalidSourceExamples: readonly string[];
  parityNotes: readonly string[];
}

/** Options for a full conversion run. */
export interface ConvertOptions {
  /** Directory holding the legacy tileset subdirectories (old/, nomad/, ...). */
  tilesRoot: string;
  /** Directory that receives one subdirectory per converted pack. */
  outputRoot: string;
  /** Pack keys to convert; all six when omitted. */
  packKeys?: readonly string[] | undefined;
  /** Progress logger; silent when omitted. */
  log?: ((message: string) => void) | undefined;
}

/** Result of a full conversion run. */
export interface ConvertSummary {
  results: readonly PackResult[];
  inventoryMarkdownPath: string;
  inventoryJsonPath: string;
}

interface Rect {
  x: number;
  y: number;
  width: number;
  height: number;
}

const PARITY_NOTES: readonly string[] = [
  "Legacy pref files are mirrored locally into the Linoleum pack folder so the mode still loads its own pref corpus.",
  "Stateful feat/trap selectors are preserved as exact loose-pack selector values with suffixes such as <selector>:lit.",
  "When a source mode uses legacy overdraw rows, the exporter keeps the bottom-anchored double-height source rectangle instead of clipping it back to one base cell.",
  "Conditional xtra remaps are preserved as exact selector values with :when:<query> suffixes and also receive one compatibility alias for the current runtime.",
  "Any source selector that points outside the original sheet is counted in the inventory and skipped rather than crashing the export.",
];

/**
 * Culture-aware, case-insensitive comparison approximating PowerShell's
 * default Sort-Object string ordering (.NET CurrentCultureIgnoreCase, which
 * is ICU-backed; Intl.Collator is ICU-backed too).
 */
const collator = new Intl.Collator("en-US", { sensitivity: "accent" });

function compareRuleOrder(a: ExportEntry, b: ExportEntry): number {
  const byType = collator.compare(a.type, b.type);
  if (byType !== 0) {
    return byType;
  }
  return collator.compare(a.selectorValue, b.selectorValue);
}

function isNullOrWhitespace(value: string | null): boolean {
  return value === null || value.trim().length === 0;
}

/** Variant preference used to pick the compatibility alias source. */
export function compatibilityVariantRank(type: string, variant: string): number {
  const typeLower = type.toLowerCase();
  if (typeLower !== "feat" && typeLower !== "trap") {
    return 0;
  }

  switch (variant.toLowerCase()) {
    case "*":
      return 0;
    case "lit":
      return 1;
    case "torch":
      return 2;
    case "los":
      return 3;
    case "dark":
      return 4;
    default:
      return 5;
  }
}

/**
 * Source rectangle for a tile, including the bottom-anchored double-height
 * extension for legacy overdraw rows.
 */
export function sourceTileRectangle(
  column: number,
  row: number,
  tileWidth: number,
  tileHeight: number,
  overdrawRow: number,
  overdrawMax: number,
): Rect {
  let sourceY = row * tileHeight;
  let sourceHeight = tileHeight;

  if (overdrawRow > 0 && row >= overdrawRow && row <= overdrawMax) {
    sourceY -= tileHeight;
    sourceHeight += tileHeight;
  }

  return { x: column * tileWidth, y: sourceY, width: tileWidth, height: sourceHeight };
}

/**
 * Family effect profile for feat LESS:/MORE: selectors (same constants as
 * the ps1). Applies only to unconditioned selectors because the exact
 * selector value must end at the variant.
 */
export function effectProfileFor(type: string, selectorValue: string): EffectProfile | null {
  if (type.toLowerCase() !== "feat") {
    return null;
  }

  if (/^LESS:(dark|lit|los|torch|\*)$/i.test(selectorValue)) {
    return { glowAlpha: 72, tint: "180,220,255,48", pulse: "168,255,1400" };
  }

  if (/^MORE:(dark|lit|los|torch|\*)$/i.test(selectorValue)) {
    return { glowAlpha: 64, tint: "255,210,150,40", pulse: "176,255,1200" };
  }

  return null;
}

/**
 * Pick the entry whose asset backs the compatibility alias: unconditioned
 * entries first, then by variant rank, then by source order.
 */
export function selectCompatibilityEntry(entries: readonly ExportEntry[]): ExportEntry | null {
  if (entries.length === 0) {
    return null;
  }

  const sorted = [...entries].sort((a, b) => {
    const condA = isNullOrWhitespace(a.condition) ? 0 : 1;
    const condB = isNullOrWhitespace(b.condition) ? 0 : 1;
    if (condA !== condB) {
      return condA - condB;
    }
    const rankA = compatibilityVariantRank(a.type, a.variant);
    const rankB = compatibilityVariantRank(b.type, b.variant);
    if (rankA !== rankB) {
      return rankA - rankB;
    }
    return a.sourceOrder - b.sourceOrder;
  });

  return sorted[0] ?? null;
}

function addUniqueExportEntry(
  entries: ExportEntry[],
  seen: Set<string>,
  entry: ExportEntry,
): void {
  const key = selectorKey(entry.type, entry.selectorValue);
  if (seen.has(key)) {
    return;
  }
  entries.push(entry);
  seen.add(key);
}

function bumpCount(counts: Record<string, number>, key: string): void {
  counts[key] = (counts[key] ?? 0) + 1;
}

function writeTextFile(path: string, lines: readonly string[]): void {
  writeFileSync(path, lines.join("\n") + "\n", { encoding: "utf8" });
}

function readPrefSources(sourceDir: string, prefFiles: readonly string[]): PrefSource[] {
  return prefFiles.map((prefFile) => {
    const path = join(sourceDir, prefFile);
    const text = readFileSync(path, "utf8");
    return { name: basename(path), lines: text.split(/\r\n|\n|\r/) };
  });
}

/** Convert one pack. Mirrors Build-PackExport. */
export function buildPackExport(
  packConfig: PackConfig,
  tilesRoot: string,
  outputRoot: string,
): PackResult {
  const sourceDir = join(tilesRoot, packConfig.sourceDirectory);
  const sheetPath = join(sourceDir, packConfig.imageFile);
  const packRoot = join(outputRoot, packConfig.key);
  const mapsDir = join(packRoot, "maps");
  const imageDir = join(packRoot, "images", String(packConfig.resolution));
  const manifestPath = join(packRoot, "manifest.txt");
  const targetMapPath = join(mapsDir, "targets.txt");
  const familyMapPath = join(mapsDir, "families.txt");
  const prefMirrorPaths: Record<string, string> = {};

  const legacyEntries = readLegacySelectors(readPrefSources(sourceDir, packConfig.prefFiles));
  const exportableEntries: ExportEntry[] = [];
  const exactRules: ExportEntry[] = [];
  const exactSeen = new Set<string>();
  const compatibilityRules: ExportEntry[] = [];
  const compatibilitySeen = new Set<string>();
  const uniqueAssets = new Set<string>();
  const legacyTypeCounts: Record<string, number> = {};
  const exactTypeCounts: Record<string, number> = {};
  const compatibilityAliasCounts: Record<string, number> = {};
  let statefulSelectorCount = 0;
  let conditionalSelectorCount = 0;
  let invalidSourceSelectorCount = 0;
  const invalidSourceExamples: string[] = [];
  const effectFamilies = new Map<string, EffectFamily>();

  const tileWidth = packConfig.tileWidth ?? packConfig.resolution;
  const tileHeight = packConfig.tileHeight ?? packConfig.resolution;
  const overdrawRow = packConfig.overdrawRow ?? 0;
  const overdrawMax = packConfig.overdrawMax ?? 0;

  for (const entry of legacyEntries) {
    bumpCount(legacyTypeCounts, entry.type);
  }

  const sheet = PNG.sync.read(readFileSync(sheetPath));
  if (sheet.width < tileWidth || sheet.height < tileHeight) {
    throw new Error(
      `Tileset image is smaller than the declared resolution for '${packConfig.key}'.`,
    );
  }

  mkdirSync(mapsDir, { recursive: true });
  mkdirSync(imageDir, { recursive: true });

  for (const prefFile of packConfig.prefFiles) {
    const sourcePrefPath = join(sourceDir, prefFile);
    const destinationPrefPath = join(packRoot, prefFile);
    copyFileSync(sourcePrefPath, destinationPrefPath);
    prefMirrorPaths[prefFile] = destinationPrefPath;
  }

  for (const entry of legacyEntries) {
    const assetName = deterministicAssetName(entry.type, entry.exactSelectorValue);
    const outputPath = join(imageDir, `${assetName}.png`);
    const rect = sourceTileRectangle(
      entry.column,
      entry.row,
      tileWidth,
      tileHeight,
      overdrawRow,
      overdrawMax,
    );
    if (
      rect.x < 0 ||
      rect.y < 0 ||
      rect.x + rect.width > sheet.width ||
      rect.y + rect.height > sheet.height
    ) {
      invalidSourceSelectorCount += 1;
      if (invalidSourceExamples.length < 5) {
        invalidSourceExamples.push(
          `${entry.type}:${entry.exactSelectorValue} -> row ${entry.row}, col ${entry.column}`,
        );
      }
      continue;
    }

    const tile = new PNG({ width: rect.width, height: rect.height });
    PNG.bitblt(sheet, tile, rect.x, rect.y, rect.width, rect.height, 0, 0);
    writeFileSync(outputPath, PNG.sync.write(tile));

    const exportEntry: ExportEntry = {
      type: entry.type,
      selectorValue: entry.exactSelectorValue,
      compatibilitySelectorValue: entry.compatibilitySelectorValue,
      assetName,
      mappingKind: "asset",
      mappingValue: assetName,
      logicalValue: entry.logicalValue,
      variant: entry.variant,
      condition: entry.condition,
      sourceLine: entry.sourceLine,
      sourceFile: entry.sourceFile,
      sourceOrder: entry.sourceOrder,
      row: entry.row,
      column: entry.column,
    };

    const effectProfile = effectProfileFor(exportEntry.type, exportEntry.selectorValue);
    if (effectProfile !== null) {
      const familyId = `${assetName}_fx`;
      exportEntry.mappingKind = "family";
      exportEntry.mappingValue = familyId;
      if (!effectFamilies.has(familyId)) {
        effectFamilies.set(familyId, {
          familyId,
          assetName,
          glowAlpha: effectProfile.glowAlpha,
          tint: effectProfile.tint,
          pulse: effectProfile.pulse,
        });
      }
    }

    exportableEntries.push(exportEntry);
    addUniqueExportEntry(exactRules, exactSeen, exportEntry);
    uniqueAssets.add(assetName);
    bumpCount(exactTypeCounts, entry.type);

    const typeLower = entry.type.toLowerCase();
    if ((typeLower === "feat" || typeLower === "trap") && entry.variant.toLowerCase() !== "*") {
      statefulSelectorCount += 1;
    }
    if (!isNullOrWhitespace(entry.condition)) {
      conditionalSelectorCount += 1;
    }
  }

  // Group by (type, compatibility selector), case-insensitively, in
  // first-appearance order (mirrors Group-Object).
  const compatibilityGroups = new Map<string, ExportEntry[]>();
  for (const entry of exportableEntries) {
    const key = selectorKey(entry.type, entry.compatibilitySelectorValue);
    const group = compatibilityGroups.get(key);
    if (group === undefined) {
      compatibilityGroups.set(key, [entry]);
    } else {
      group.push(entry);
    }
  }

  for (const group of compatibilityGroups.values()) {
    const selected = selectCompatibilityEntry(group);
    if (selected === null) {
      continue;
    }
    const needsAlias =
      selected.selectorValue.toLowerCase() !==
      selected.compatibilitySelectorValue.toLowerCase();
    if (!needsAlias) {
      continue;
    }

    const aliasEntry: ExportEntry = {
      ...selected,
      selectorValue: selected.compatibilitySelectorValue,
    };
    addUniqueExportEntry(compatibilityRules, compatibilitySeen, aliasEntry);
    bumpCount(compatibilityAliasCounts, selected.type);
  }

  const manifestLines: string[] = [
    `pack:${packConfig.packId}:${packConfig.displayName}`,
    "format:png",
    `resolution:${packConfig.resolution}`,
    "map:targets:maps/targets.txt",
  ];
  if (effectFamilies.size > 0) {
    manifestLines.push("map:families:maps/families.txt");
  }
  writeTextFile(manifestPath, manifestLines);

  if (effectFamilies.size > 0) {
    const familyMapLines: string[] = [
      GENERATED_BY,
      "# Family effect metadata stays behind stable target selector syntax.",
      "",
    ];
    const families = [...effectFamilies.values()].sort((a, b) =>
      collator.compare(a.familyId, b.familyId),
    );
    for (const family of families) {
      familyMapLines.push(`family:${family.familyId}:selection:stable`);
      familyMapLines.push(`family:${family.familyId}:asset:${family.assetName}`);
      familyMapLines.push(`family:${family.familyId}:glow-alpha:${family.glowAlpha}`);
      familyMapLines.push(`family:${family.familyId}:tint:${family.tint}`);
      familyMapLines.push(`family:${family.familyId}:pulse:${family.pulse}`);
      familyMapLines.push("");
    }
    writeTextFile(familyMapPath, familyMapLines);
  } else if (existsSync(familyMapPath)) {
    rmSync(familyMapPath, { force: true });
  }

  const targetMapLines: string[] = [
    GENERATED_BY,
    "# Compatibility aliases come first so current unsuffixed runtime lookups stay usable.",
    "",
  ];
  for (const entry of [...compatibilityRules].sort(compareRuleOrder)) {
    targetMapLines.push(
      `target:${entry.type}:${entry.selectorValue}:${entry.mappingKind}:${entry.mappingValue}`,
    );
  }
  if (compatibilityRules.length > 0) {
    targetMapLines.push("");
  }
  targetMapLines.push("# Exact legacy selectors, including stateful and conditional variants.");
  for (const entry of [...exactRules].sort(compareRuleOrder)) {
    targetMapLines.push(
      `target:${entry.type}:${entry.selectorValue}:${entry.mappingKind}:${entry.mappingValue}`,
    );
  }
  writeTextFile(targetMapPath, targetMapLines);

  return {
    key: packConfig.key,
    displayName: packConfig.displayName,
    sourceMode: packConfig.sourceMode,
    sourceDirectory: packConfig.sourceDirectory,
    resolution: packConfig.resolution,
    packRoot,
    manifestPath,
    targetMapPath,
    familyMapPath,
    prefFiles: packConfig.prefFiles,
    prefMirrorPaths,
    legacyTypeCounts,
    exactTypeCounts,
    compatibilityAliasCounts,
    exactSelectorCount: exactRules.length,
    compatibilityAliasCount: compatibilityRules.length,
    totalTargetRuleCount: exactRules.length + compatibilityRules.length,
    assetCount: uniqueAssets.size,
    statefulSelectorCount,
    conditionalSelectorCount,
    invalidSourceSelectorCount,
    invalidSourceExamples,
    parityNotes: PARITY_NOTES,
  };
}

function formatLocalTimestamp(date: Date): string {
  const pad = (n: number): string => String(n).padStart(2, "0");
  const offsetMinutes = -date.getTimezoneOffset();
  const sign = offsetMinutes >= 0 ? "+" : "-";
  const absMinutes = Math.abs(offsetMinutes);
  const offset = `${sign}${pad(Math.floor(absMinutes / 60))}:${pad(absMinutes % 60)}`;
  return (
    `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ` +
    `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())} ${offset}`
  );
}

/** Write the Markdown inventory report. Mirrors Write-InventoryMarkdown. */
export function writeInventoryMarkdown(
  packResults: readonly PackResult[],
  path: string,
  tilesRoot: string,
  outputRoot: string,
): void {
  const lines: string[] = [];
  lines.push("# Linoleum bundled tileset inventory");
  lines.push("");
  lines.push(`- Generated: \`${formatLocalTimestamp(new Date())}\``);
  lines.push(`- Scope: bundled legacy tileset conversions under \`${outputRoot}\``);
  lines.push("- Output types: Markdown summary + machine-readable JSON companion");
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(
    "| Pack | Source mode | Resolution | Assets | Exact selectors | Compatibility aliases | Stateful selectors | Conditional selectors | Total target rules |",
  );
  lines.push("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");
  for (const result of packResults) {
    lines.push(
      `| ${result.displayName} | ${result.sourceMode} | ${result.resolution} | ${result.assetCount} | ${result.exactSelectorCount} | ${result.compatibilityAliasCount} | ${result.statefulSelectorCount} | ${result.conditionalSelectorCount} | ${result.totalTargetRuleCount} |`,
    );
  }
  lines.push("");
  lines.push("## Coverage notes");
  lines.push("");
  lines.push(
    "- Each converted pack mirrors its original pref files into its own Linoleum folder so the mode keeps loading local legacy mapping truth rather than falling back to a placeholder pref stub.",
  );
  lines.push(
    "- `maps/targets.txt` preserves exact legacy selectors for stateful terrain and traps by encoding selectors such as `feat:FLOOR:lit` or `trap:pit:dark` as first-class loose-pack target keys.",
  );
  lines.push(
    "- Conditional `xtra` remaps are preserved as exact selector values with `:when:<query>` suffixes, and each pack also ships one compatibility alias per base selector for the current runtime.",
  );
  lines.push(
    "- The current runtime still resolves only the compatibility alias layer for several legacy dimensions, so the alias counts quantify where further exact-parity runtime work is still needed.",
  );
  lines.push("");
  lines.push("## Per-pack detail");
  lines.push("");
  for (const result of packResults) {
    const prefList = result.prefFiles.map((pref) => `\`${pref}\``).join(", ");
    lines.push(`### ${result.displayName}`);
    lines.push("");
    lines.push(`- Source mode: \`${result.sourceMode}\``);
    lines.push(`- Source directory: \`${join(tilesRoot, result.sourceDirectory)}\``);
    lines.push(`- Linoleum root: \`${result.packRoot}\``);
    lines.push(`- Mirrored pref files: ${prefList}`);
    lines.push(`- Asset count: \`${result.assetCount}\``);
    lines.push(`- Exact selector count: \`${result.exactSelectorCount}\``);
    lines.push(`- Compatibility alias count: \`${result.compatibilityAliasCount}\``);
    lines.push(`- Stateful selectors preserved: \`${result.statefulSelectorCount}\``);
    lines.push(`- Conditional selectors preserved: \`${result.conditionalSelectorCount}\``);
    lines.push(`- Invalid source selectors skipped: \`${result.invalidSourceSelectorCount}\``);
    if (result.invalidSourceExamples.length > 0) {
      const invalidExamples = result.invalidSourceExamples
        .map((example) => `\`${example}\``)
        .join("; ");
      lines.push(`- Example invalid selectors: ${invalidExamples}`);
    }
    lines.push("");
  }

  writeTextFile(path, lines);
}

/**
 * Run the converter for the requested packs and write the inventory
 * reports into the output root.
 */
export function convertPacks(options: ConvertOptions): ConvertSummary {
  const log = options.log ?? ((): void => {});
  const selectedPacks = selectPacks(options.packKeys);

  mkdirSync(options.outputRoot, { recursive: true });

  const results: PackResult[] = [];
  for (const pack of selectedPacks) {
    log(`Building Linoleum pack: ${pack.displayName}`);
    results.push(buildPackExport(pack, options.tilesRoot, options.outputRoot));
  }

  const inventoryMarkdownPath = join(options.outputRoot, "graphics-linoleum-inventory.md");
  const inventoryJsonPath = join(options.outputRoot, "graphics-linoleum-inventory.json");

  writeInventoryMarkdown(results, inventoryMarkdownPath, options.tilesRoot, options.outputRoot);

  const inventory = {
    generatedAt: new Date().toISOString(),
    outputRoot: options.outputRoot,
    packCount: results.length,
    packs: results,
  };
  writeFileSync(inventoryJsonPath, JSON.stringify(inventory, null, 2) + "\n", {
    encoding: "utf8",
  });

  log(`Built ${results.length} Linoleum pack(s).`);
  log(`Markdown inventory: ${inventoryMarkdownPath}`);
  log(`JSON inventory: ${inventoryJsonPath}`);

  return { results, inventoryMarkdownPath, inventoryJsonPath };
}
