/**
 * Unit tests for the target-map / variant-pool model: parsing (including
 * colon-bearing selectors and the new `pool` kind), pool parsing, formatting
 * round-trips, and the deterministic pool selection rule.
 */

import { describe, expect, it } from "vitest";
import {
  formatPoolLines,
  formatTargetRule,
  parsePoolsFile,
  parseTargetLine,
  parseTargetsFile,
  selectPoolMember,
} from "./targets.js";
import type { PoolDefinition } from "./targets.js";

describe("parseTargetLine", () => {
  it("parses an asset rule", () => {
    expect(parseTargetLine("target:feat:FLOOR:asset:feat_floor_lit_0")).toEqual({
      type: "feat",
      selector: "FLOOR",
      kind: "asset",
      value: "feat_floor_lit_0",
    });
  });

  it("parses a family rule", () => {
    expect(parseTargetLine("target:feat:LESS:family:feat_less_lit_0_fx")).toEqual({
      type: "feat",
      selector: "LESS",
      kind: "family",
      value: "feat_less_lit_0_fx",
    });
  });

  it("parses a pool rule (new kind)", () => {
    expect(parseTargetLine("target:feat:FLOOR:pool:floor_variants")).toEqual({
      type: "feat",
      selector: "FLOOR",
      kind: "pool",
      value: "floor_variants",
    });
  });

  it("keeps colons inside the selector (GF:ELEC:0)", () => {
    expect(parseTargetLine("target:GF:ELEC:0:asset:gf_elec_0_0")).toEqual({
      type: "GF",
      selector: "ELEC:0",
      kind: "asset",
      value: "gf_elec_0_0",
    });
  });

  it("keeps colons in a per-object selector", () => {
    expect(
      parseTargetLine("target:object:light:Wooden Torch:pool:torch_variants"),
    ).toEqual({
      type: "object",
      selector: "light:Wooden Torch",
      kind: "pool",
      value: "torch_variants",
    });
  });

  it("rejects comments, blanks, unknown kinds, and short lines", () => {
    expect(parseTargetLine("# a comment")).toBeNull();
    expect(parseTargetLine("")).toBeNull();
    expect(parseTargetLine("target:feat:FLOOR:bogus:x")).toBeNull();
    expect(parseTargetLine("target:feat:asset")).toBeNull();
  });
});

describe("parseTargetsFile", () => {
  it("parses only target rules, in order, skipping headers/blanks", () => {
    const text = [
      "# Generated by @neo-angband/linoleum",
      "",
      "target:feat:FLOOR:asset:feat_floor_lit_0",
      "target:feat:FLOOR:pool:floor_variants",
    ].join("\n");
    const rules = parseTargetsFile(text);
    expect(rules).toHaveLength(2);
    expect(rules[1]?.kind).toBe("pool");
  });
});

describe("pool parse/format round-trip", () => {
  const pool: PoolDefinition = {
    poolId: "floor_variants",
    selection: "stable",
    members: ["feat_floor_lit_0", "feat_floor_dark_0", "feat_floor_los_0"],
  };

  it("formats then parses back to the same definition", () => {
    const text = formatPoolLines(pool).join("\n");
    expect(parsePoolsFile(text)).toEqual([pool]);
  });

  it("defaults selection to stable and accumulates members in order", () => {
    const text = [
      "pool:p:member:a",
      "pool:p:member:b",
    ].join("\n");
    expect(parsePoolsFile(text)).toEqual([
      { poolId: "p", selection: "stable", members: ["a", "b"] },
    ]);
  });

  it("parses the index selection rule", () => {
    const text = "pool:p:selection:index\npool:p:member:a";
    expect(parsePoolsFile(text)[0]?.selection).toBe("index");
  });

  it("formatTargetRule round-trips through parseTargetLine", () => {
    const rule = {
      type: "object" as const,
      selector: "light:Wooden Torch",
      kind: "pool" as const,
      value: "torch_variants",
    };
    expect(parseTargetLine(formatTargetRule(rule))).toEqual(rule);
  });
});

describe("selectPoolMember", () => {
  const stable: PoolDefinition = {
    poolId: "floor_variants",
    selection: "stable",
    members: ["a", "b", "c", "d"],
  };
  const indexed: PoolDefinition = {
    poolId: "torch_variants",
    selection: "index",
    members: ["x", "y", "z"],
  };

  it("is deterministic: same grid -> same member", () => {
    const first = selectPoolMember(stable, { x: 12, y: 7 });
    const again = selectPoolMember(stable, { x: 12, y: 7 });
    expect(first).toBe(again);
    expect(stable.members).toContain(first);
  });

  it("varies across grid cells (stable rule distributes)", () => {
    const seen = new Set<string>();
    for (let x = 0; x < 20; x++) {
      for (let y = 0; y < 20; y++) {
        const m = selectPoolMember(stable, { x, y });
        if (m) seen.add(m);
      }
    }
    // With 400 cells over 4 members, every member should appear.
    expect(seen.size).toBe(4);
  });

  it("index rule selects by explicit ordinal, wrapping", () => {
    expect(selectPoolMember(indexed, { x: 0, y: 0, index: 0 })).toBe("x");
    expect(selectPoolMember(indexed, { x: 0, y: 0, index: 1 })).toBe("y");
    expect(selectPoolMember(indexed, { x: 0, y: 0, index: 2 })).toBe("z");
    expect(selectPoolMember(indexed, { x: 0, y: 0, index: 3 })).toBe("x");
  });

  it("index rule falls back to x+y when no ordinal is given", () => {
    expect(selectPoolMember(indexed, { x: 1, y: 1 })).toBe(
      indexed.members[2],
    );
  });

  it("wraps negative ordinals into range", () => {
    const m = selectPoolMember(indexed, { x: 0, y: 0, index: -1 });
    expect(indexed.members).toContain(m);
  });

  it("returns null for an empty pool", () => {
    expect(
      selectPoolMember({ poolId: "e", selection: "stable", members: [] }, { x: 0, y: 0 }),
    ).toBeNull();
  });
});
