#!/usr/bin/env node
/**
 * The surface a mod's code can reach, recorded so it cannot move by accident.
 *
 * WHY. `ctx.core` is the live core module namespace - the whole engine, not a
 * curated slice (packages/web/src/mod-plugin.ts says so in as many words, and
 * ratified decision 18 is that this is deliberate). `MOD_API_VERSION` covers
 * the SHAPE of the plugin contract, not the names behind `ctx.core`. Rename
 * one and every plugin using it breaks - at runtime, in a player's browser.
 *
 * This tool is the ratchet over the whole set: a removal or addition fails,
 * the baseline is updated, and a known break is recorded. A named subset of
 * `ctx.core` is separately guaranteed (`packages/core/mod-core-guaranteed.json`,
 * `mod-core-guaranteed.test.ts`); updating this baseline is not enough to drop
 * one of those names.
 *
 * That is the SKSE-shaped hole for the namespace as a whole, and it cannot be
 * closed by taking the namespace away (decision 18) or by hand-curating what a
 * plugin may see. A named subset of `ctx.core` is guaranteed separately. This
 * tool is the ratchet over everything else: a removal is deliberate, recorded,
 * and visible.
 *
 * TWO SURFACES, NOT ONE, since `ctx.authoring` landed. That field is the mod
 * SDK's public barrel handed in whole, the same way `ctx.core` is, so it
 * arrived carrying the same hole and closes it the same way (a ratchet, not a
 * named subset). The SDK was out of scope here while it was only a build-time
 * dependency of the host; it is now a namespace a plugin holds at runtime, and
 * a rename inside it costs a mod author the same silent breakage.
 *
 * WHY BOTH DIRECTIONS. A baseline that only failed on removals would go stale -
 * an export added in one release and removed in the next would never have been
 * in the file, so nothing would notice it going. Failing on additions costs one
 * `--update` run per release and keeps the record complete, which is the only
 * state in which the removal check means anything.
 *
 * RUNTIME KEYS, NOT TYPES, and that is the right measurement rather than a
 * limitation: a plugin ships as built JavaScript, so a renamed interface cannot
 * break it and a renamed function can.
 *
 *   node tools/api-surface.mjs           # check both, exit 1 on drift
 *   node tools/api-surface.mjs --update  # rewrite both baselines
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

/**
 * The surfaces watched, each named for the ctx field that hands it over.
 *
 * `baseline` sits inside the package whose exports it records rather than in a
 * shared folder, so a reader who opens the package finds the record of what it
 * promises without knowing this tool exists.
 */
export const SURFACES = [
  {
    field: "ctx.core",
    baseline: resolve(here, "../packages/core/mod-api-surface.json"),
    built: resolve(here, "../packages/core/dist/index.js"),
    note:
      "Every runtime export a mod plugin can reach through ctx.core. Generated by " +
      "tools/api-surface.mjs; removing a name from this list is removing it from " +
      "every mod that uses it. See docs/modding/MOD_COMPATIBILITY.md.",
  },
  {
    field: "ctx.authoring",
    baseline: resolve(here, "../packages/mod-sdk/mod-sdk-api-surface.json"),
    built: resolve(here, "../packages/mod-sdk/dist/index.js"),
    note:
      "Every runtime export a mod plugin can reach through ctx.authoring. Generated by " +
      "tools/api-surface.mjs; removing a name from this list is removing it from " +
      "every mod that uses it. See docs/modding/MOD_COMPATIBILITY.md.",
  },
];

/** The built package's namespace keys, sorted - what a plugin actually gets. */
export async function currentSurface(surface = SURFACES[0]) {
  const mod = await import(`file://${surface.built.replaceAll("\\", "/")}`);
  return Object.keys(mod).sort();
}

/** The recorded baseline, or null when there is not one yet. */
export function baselineSurface(surface = SURFACES[0]) {
  try {
    return JSON.parse(readFileSync(surface.baseline, "utf8")).exports;
  } catch {
    return null;
  }
}

/** What changed, in both directions. */
export function surfaceDrift(baseline, current) {
  const was = new Set(baseline);
  const now = new Set(current);
  return {
    removed: baseline.filter((n) => !now.has(n)),
    added: current.filter((n) => !was.has(n)),
  };
}

export function writeBaseline(current, surface = SURFACES[0]) {
  writeFileSync(
    surface.baseline,
    `${JSON.stringify({ note: surface.note, exports: current }, null, 2)}\n`,
  );
}

/** Check one surface. Returns true when it is clean. */
async function checkSurface(surface) {
  const current = await currentSurface(surface);
  const baseline = baselineSurface(surface);
  if (!baseline) {
    console.error(`api-surface: no baseline for ${surface.field}; run with --update`);
    return false;
  }
  const { removed, added } = surfaceDrift(baseline, current);
  if (removed.length === 0 && added.length === 0) {
    console.log(`api-surface: ${surface.field}, ${current.length} exports, unchanged`);
    return true;
  }
  if (removed.length > 0) {
    console.error(
      `api-surface: ${removed.length} export(s) GONE from the surface mods reach ` +
        `through ${surface.field}:\n  ${removed.join("\n  ")}\n` +
        "Every plugin using one of these breaks, at runtime, in a player's browser.",
    );
    if (surface.field === "ctx.core") {
      const guaranteedFile = resolve(here, "../packages/core/mod-core-guaranteed.json");
      const guaranteed = new Set(
        JSON.parse(readFileSync(guaranteedFile, "utf8")).exports.map((entry) => entry.name),
      );
      const broken = removed.filter((name) => guaranteed.has(name));
      if (broken.length > 0) {
        console.error(
          `api-surface: ${broken.length} of those are GUARANTEED ctx.core exports:\n  ` +
            `${broken.join("\n  ")}\n` +
            "Keep the old name as an alias, or take the two-release modApi path. " +
            "Updating this baseline is not enough. See docs/modding/MOD_COMPATIBILITY.md.",
        );
      }
    }
  }
  if (added.length > 0) {
    console.error(
      `api-surface: ${added.length} new export(s) on ${surface.field}:\n  ${added.join("\n  ")}`,
    );
  }
  return false;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replaceAll("\\", "/"))) {
  if (process.argv.includes("--update")) {
    for (const surface of SURFACES) {
      const current = await currentSurface(surface);
      writeBaseline(current, surface);
      console.log(`api-surface: recorded ${current.length} exports for ${surface.field}`);
    }
    process.exit(0);
  }
  /* Every surface is checked before anything exits, so one run names both
   * problems rather than sending the reader round the loop twice. */
  let clean = true;
  for (const surface of SURFACES) {
    if (!(await checkSurface(surface))) clean = false;
  }
  if (clean) process.exit(0);
  console.error("Run `node tools/api-surface.mjs --update` once the change is intended.");
  process.exit(1);
}
