#!/usr/bin/env node
/**
 * The surface a mod's code can reach, recorded so it cannot move by accident.
 *
 * WHY. `ctx.core` is the live core module namespace - the whole engine, not a
 * curated slice (packages/web/src/mod-plugin.ts says so in as many words, and
 * ratified decision 18 is that this is deliberate). It is also completely
 * unguarded: `MOD_API_VERSION` covers the SHAPE of the plugin contract, and
 * nothing at all covers the 1700-odd names behind `ctx.core`. Rename one and
 * every plugin using it breaks - at runtime, in a player's browser, with no
 * error anywhere in this repository and nothing in CI that could have known.
 *
 * That is the SKSE-shaped hole, and it cannot be closed by taking the namespace
 * away (decision 18) or by hand-curating a smaller one (the curated list is the
 * thing that drifts). What it CAN be closed by is making a removal deliberate:
 * this records every runtime export, and the test beside it fails when the set
 * changes in either direction.
 *
 * WHY BOTH DIRECTIONS. A baseline that only failed on removals would go stale -
 * an export added in one release and removed in the next would never have been
 * in the file, so nothing would notice it going. Failing on additions costs one
 * `--update` run per release and keeps the record complete, which is the only
 * state in which the removal check means anything.
 *
 * RUNTIME KEYS, NOT TYPES, and that is the right measurement rather than a
 * limitation: a plugin ships as built JavaScript, so a renamed interface cannot
 * break it and a renamed function can.
 *
 *   node tools/api-surface.mjs           # check, exit 1 on drift
 *   node tools/api-surface.mjs --update  # rewrite the baseline
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const BASELINE = resolve(here, "../packages/core/mod-api-surface.json");
const BUILT = resolve(here, "../packages/core/dist/index.js");

const NOTE =
  "Every runtime export a mod plugin can reach through ctx.core. Generated by " +
  "tools/api-surface.mjs; removing a name from this list is removing it from " +
  "every mod that uses it. See docs/modding/MOD_COMPATIBILITY.md.";

/** The built package's namespace keys, sorted - what a plugin actually gets. */
export async function currentSurface() {
  const mod = await import(`file://${BUILT.replaceAll("\\", "/")}`);
  return Object.keys(mod).sort();
}

/** The recorded baseline, or null when there is not one yet. */
export function baselineSurface() {
  try {
    return JSON.parse(readFileSync(BASELINE, "utf8")).exports;
  } catch {
    return null;
  }
}

/** What changed, in both directions. */
export function surfaceDrift(baseline, current) {
  const was = new Set(baseline);
  const now = new Set(current);
  return {
    removed: baseline.filter((n) => !now.has(n)),
    added: current.filter((n) => !was.has(n)),
  };
}

export function writeBaseline(current) {
  writeFileSync(BASELINE, `${JSON.stringify({ note: NOTE, exports: current }, null, 2)}\n`);
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replaceAll("\\", "/"))) {
  const current = await currentSurface();
  if (process.argv.includes("--update")) {
    writeBaseline(current);
    console.log(`api-surface: recorded ${current.length} exports`);
    process.exit(0);
  }
  const baseline = baselineSurface();
  if (!baseline) {
    console.error("api-surface: no baseline; run with --update");
    process.exit(1);
  }
  const { removed, added } = surfaceDrift(baseline, current);
  if (removed.length === 0 && added.length === 0) {
    console.log(`api-surface: ${current.length} exports, unchanged`);
    process.exit(0);
  }
  if (removed.length > 0) {
    console.error(
      `api-surface: ${removed.length} export(s) GONE from the surface mods reach ` +
        `through ctx.core:\n  ${removed.join("\n  ")}\n` +
        "Every plugin using one of these breaks, at runtime, in a player's browser.",
    );
  }
  if (added.length > 0) {
    console.error(`api-surface: ${added.length} new export(s):\n  ${added.join("\n  ")}`);
  }
  console.error("Run `node tools/api-surface.mjs --update` once the change is intended.");
  process.exit(1);
}
