#!/usr/bin/env python3
"""Regenerate a packages/web/src/font-<w>x<h>.ts module from an Angband .fon.

The Windows/SDL front ends blit a fixed bitmap font. Those .fon files are
Windows NE executables wrapping an RT_FONT resource (a FNT v2/v3 bitmap). This
reads the first FNT resource and emits a typed TS module of 256 glyphs (CP437
order) that GlyphTerm blits and tints per attr, so the web terminal shows the
ORIGINAL glyphs, not a system monospace substitute. The export name and header
are derived from the font's pixel dimensions, so the tool is source-agnostic.

The .fon glyphs are GPL (reference/docs/copying.rst): by Leon Marrick, Sheldon
Simms III and/or Nick McConnell. reference/ is not tracked in this repo, so this
is a dev-time regeneration step; the generated font-<w>x<h>.ts is what ships.

Usage (from the repo root):
    python packages/web/scripts/extract-fon.py \
        reference/lib/fonts/16x24x.fon packages/web/src/font-16x24.ts
"""
import os
import struct
import sys


def u8(b, o):
    return b[o]


def u16(b, o):
    return struct.unpack_from("<H", b, o)[0]


def u32(b, o):
    return struct.unpack_from("<I", b, o)[0]


def find_first_fnt(data):
    """Return (offset, length) of the first RT_FONT resource in an NE .fon."""
    ne = u32(data, 0x3C)
    assert data[ne:ne + 2] == b"NE", "not an NE executable"
    rsrc_off = ne + u16(data, ne + 0x24)  # ne_rsrctab
    align = u16(data, rsrc_off)
    p = rsrc_off + 2
    while True:
        type_id = u16(data, p)
        p += 2
        if type_id == 0:
            break
        count = u16(data, p)
        p += 2
        p += 4  # reserved
        for _ in range(count):
            off = u16(data, p) << align
            length = u16(data, p + 2) << align
            p += 12  # NAMEINFO
            if type_id == 0x8008:  # RT_FONT
                return off, length
    raise RuntimeError("no RT_FONT resource found")


def parse_fnt(data, base):
    """Parse a FNT v2/v3 resource into {code: [row masks]} for a fixed font."""
    ver = u16(data, base + 0)
    px_w = u16(data, base + 0x56)
    px_h = u16(data, base + 0x58)
    first = u8(data, base + 0x5F)
    last = u8(data, base + 0x60)
    ct = base + (0x94 if ver >= 0x300 else 0x76)  # char table start
    ent = 6 if ver >= 0x300 else 4  # GLYPHENTRY size
    glyphs = {}
    for i in range(last - first + 1):
        ge = ct + i * ent
        gw = u16(data, ge)
        goff = u32(data, ge + 2) if ver >= 0x300 else u16(data, ge + 2)
        cols = (gw + 7) // 8
        rows = []
        for r in range(px_h):
            # FNT is column-major: byte (col-block c, row r) at goff+c*px_h+r,
            # merged left-to-right, then shifted so bit gw-1 is the leftmost.
            mask = 0
            for c in range(cols):
                mask |= data[base + goff + c * px_h + r] << (8 * (cols - 1 - c))
            rows.append(mask >> (8 * cols - gw) if gw else 0)
        glyphs[first + i] = rows
    return ver, px_w, px_h, glyphs


def main():
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "rb") as f:
        data = f.read()
    off, _ = find_first_fnt(data)
    ver, w, h, glyphs = parse_fnt(data, off)
    blank = [0] * h
    name = f"FONT_{w}X{h}"
    srcbase = os.path.basename(src)
    out = []
    out.append("// Auto-generated by packages/web/scripts/extract-fon.py from the Angband")
    out.append(f"// terminal font reference/lib/fonts/{srcbase}. The .fon glyphs are GPL, by")
    out.append("// Leon Marrick, Sheldon Simms III and/or Nick McConnell")
    out.append("// (reference/docs/copying.rst).")
    out.append("// Do not hand-edit; re-run the extractor to regenerate.")
    out.append("//")
    out.append("// Each glyph is H row bitmasks, MSB (bit W-1) = leftmost pixel. Codes 0-255")
    out.append("// in CP437 order, exactly as the Windows/SDL front ends blit them.")
    out.append("")
    out.append("export interface BitmapFontData {")
    out.append("  readonly w: number;")
    out.append("  readonly h: number;")
    out.append("  readonly glyphs: readonly (readonly number[])[];")
    out.append("}")
    out.append("")
    out.append(f"export const {name}: BitmapFontData = {{")
    out.append(f"  w: {w},")
    out.append(f"  h: {h},")
    out.append("  glyphs: [")
    for code in range(256):
        rows = glyphs.get(code, blank)
        out.append("    [" + ",".join(str(r) for r in rows) + f"], // {code}")
    out.append("  ],")
    out.append("};")
    with open(dst, "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    sys.stderr.write(
        f"wrote {dst}: FNT v0x{ver:04x} {w}x{h}, 256 glyphs\n"
    )


if __name__ == "__main__":
    main()
